<?php
/**
*
* This file is part of the phpBB Forum Software package.
*
* @copyright (c) phpBB Limited <https://www.phpbb.com>
* @license GNU General Public License, version 2 (GPL-2.0)
*
* For full copyright and license information, please see
* the docs/CREDITS.txt file.
*
*/

/**
* DO NOT CHANGE
*/
if (!defined('IN_PHPBB'))
{
	exit;
}

if (empty($lang) || !is_array($lang))
{
	$lang = array();
}

// DEVELOPERS PLEASE NOTE
//
// All language files should use UTF-8 as their encoding and the files must not contain a BOM.
//
// Placeholders can now contain order information, e.g. instead of
// 'Page %s of %s' you can (and should) write 'Page %1$s of %2$s', this allows
// translators to re-order the output of data while ensuring it remains correct
//
// You do not need this where single placeholders are used, e.g. 'Message %d' is fine
// equally where a string contains only two placeholders which are used to wrap text
// in a url you again do not need to specify an order e.g., 'Click %sHERE%s' is fine
//
// Some characters you may want to copy&paste:
// ’ » “ ” …
//

$lang = array_merge($lang, array(
	'TRANSLATION_INFO'	=> 'Превод от <a href="http://www.ladaclub-bg.com/" target="_blank">Денис Иванов</а>',
	'DIRECTION'			=> 'ltr',
	'DATE_FORMAT'		=> '|d M Y|',	// 01 Jan 2007 (with Relative days enabled)
	'DATETIME_FORMAT'	=> '|d M Y, H:i|',	// 01 Jan 2007, 13:37 (with Relative days enabled)
	'USER_LANG'			=> 'bg-bg',

	// You can define different rules for the determination of plural forms here.
	// See http://wiki.phpbb.com/Plural_Rules for more information
	// or ask the translation manager for help.
	'PLURAL_RULE'		=> 1,

	'1_DAY'			=> '1 ден',
	'1_MONTH'		=> '1 месец',
	'1_YEAR'		=> '1 година',
	'2_WEEKS'		=> '2 седмици',
	'3_MONTHS'		=> '3 месеца',
	'6_MONTHS'		=> '6 месеца',
	'7_DAYS'		=> '7 дни',

	'ACCOUNT_ALREADY_ACTIVATED'		=> 'Профилът Ви вече е активиран.',
	'ACCOUNT_DEACTIVATED'			=> 'Профилът Ви е ръчно деактивиран и може да бъде активиран отново само от администратор.',
	'ACCOUNT_NOT_ACTIVATED'			=> 'Профилът Ви все още не е активиран.',
	'ACP'							=> 'Административен панел',
	'ACP_SHORT'						=> 'АКП',
	'ACTIVE'						=> 'активен',
	'ACTIVE_ERROR'					=> 'Избраният потребител не е активиран. Ако имате проблеми с активацията на профила, моля обърнете се към администратора.',
	'ADMINISTRATOR'					=> 'Администратор',
	'ADMINISTRATORS'				=> 'Администратори',
	'AGE'							=> 'Години',
	'AIM'							=> 'AIM',
	'AJAX_ERROR_TITLE'				=> 'AJAX грешка',
	'AJAX_ERROR_TEXT'				=> 'Нещо се обърка при обработката на заявката.',
	'AJAX_ERROR_TEXT_ABORT'			=> 'Заявката е прекратена от потребителя.',
	'AJAX_ERROR_TEXT_TIMEOUT'		=> 'Времето за изпълнение на заявката Ви изтече; моля опитайте отново.',
	'AJAX_ERROR_TEXT_PARSERERROR'	=> 'Нещо се обърка със заявката и сървърът върна невалиден отговор.',
	'ALLOWED'						=> 'Позволен',
	'ALL_FILES'						=> 'Всички файлове',
	'ALL_FORUMS'					=> 'Всички форуми',
	'ALL_MESSAGES'					=> 'Всички съобщения',
	'ALL_POSTS'						=> 'Всички мнения',
	'ALL_TIMES'						=> 'Всички времена са <abbr title="%2$s">%1$s</abbr>',
	'ALL_TOPICS'					=> 'Всички теми',
	'AND'							=> 'и',
	'ARE_WATCHING_FORUM'			=> 'Вие се абонирахте да бъдете уведомявани за нови мнения в този форум.',
	'ARE_WATCHING_TOPIC'			=> 'Вие се абонирахте да бъдете уведомявани за нови мнения в тази тема.',
	'ASCENDING'						=> 'Възходящ',
	'ATTACHMENTS'					=> 'Прикачени файлове',
	'ATTACHED_IMAGE_NOT_IMAGE'		=> 'Изображението, което се опитахте да прикачите е невалидно.',
	'AUTHOR'						=> 'Автор',
	'AUTH_NO_PROFILE_CREATED'		=> 'Създаването на потребителски профил беше неуспешно.',
	'AUTH_PROVIDER_OAUTH_ERROR_INVALID_ENTRY'				=> 'Невалиден запис в базата данни.',
	'AUTH_PROVIDER_OAUTH_ERROR_INVALID_SERVICE_TYPE'		=> 'Невалиден тип на услугата е подаден на OAuth сървъра.',
	'AUTH_PROVIDER_OAUTH_ERROR_SERVICE_NOT_CREATED'			=> 'OAuth услугата не е създадена',
	'AUTH_PROVIDER_OAUTH_SERVICE_BITLY'						=> 'Bitly',
	'AUTH_PROVIDER_OAUTH_SERVICE_FACEBOOK'					=> 'Facebook',
	'AUTH_PROVIDER_OAUTH_SERVICE_GOOGLE'					=> 'Google',
	'AUTH_PROVIDER_OAUTH_TOKEN_ERROR_NOT_STORED'			=> 'OAuth token не е записан.',
	'AUTH_PROVIDER_OAUTH_TOKEN_ERROR_INCORRECTLY_STORED'	=> 'OAuth token е неправилно записан.',
	'AVATAR_DISALLOWED_CONTENT'		=> 'Прикаченият файл беше отхвърлен, защото е идентифициран като потенциална заплаха.',
	'AVATAR_DISALLOWED_EXTENSION'	=> 'Файлът не може да бъде показан, защото разширението <strong>%s</strong> не е разрешено.',
	'AVATAR_EMPTY_REMOTE_DATA'		=> 'Избраният аватар не може да бъде качен, защото отдалеченият файл е невалиден или счупен.',
	'AVATAR_EMPTY_FILEUPLOAD'		=> 'Каченият аватар е празен.',
	'AVATAR_INVALID_FILENAME'		=> '%s е невалидно име на файл.',
	'AVATAR_NOT_UPLOADED'			=> 'Аватарът не може да бъде качен.',
	'AVATAR_NO_SIZE'				=> 'Ширината или височината на свързаният аватар не могат да бъдат определени. Моля, въведете ги ръчно.',
	'AVATAR_PARTIAL_UPLOAD'			=> 'Избраният файл беше частично качен.',
	'AVATAR_PHP_SIZE_NA'			=> 'Рзмерът на аватара е твърде голям.<br />Максималният позволен размер на файла в php.ini не може да бъде определен.',
	'AVATAR_PHP_SIZE_OVERRUN'		=> 'Размерът на аватара е твърде голям. Максималният позволен размер на файла е %1$d %2$s.<br />Този размер е зададен в php.ini и не може да бъде променен.',
	'AVATAR_REMOTE_UPLOAD_TIMEOUT'		=> 'Избраният аватар не може да бъде качен, защото времето за изпълнение на заявката изтече.',
	'AVATAR_URL_INVALID'			=> 'Адресът, който избрахте е невалиден.',
	'AVATAR_URL_NOT_FOUND'			=> 'Избраният файл не може да бъде намерен.',
	'AVATAR_WRONG_FILESIZE'			=> 'Големината на аватара тряба да е между 0 и %1$d %2$s.',
	'AVATAR_WRONG_SIZE'				=> 'Избраният аватар е широк %5$s и висок %6$s. Аватарите трябва да са широки поне %1$s и високи поне %2$s, но не по-широки от %3$s и по-високи от %4$s.',

	'BACK_TO_TOP'			=> 'Нагоре',
	'BACK_TO_PREV'			=> 'Върни се на предишната страница',
	'BAN_TRIGGERED_BY_EMAIL'=> 'Потребителят с този емейл адрес е изгонен от форума.',
	'BAN_TRIGGERED_BY_IP'	=> 'Потребителят с този IP адрес е изгонен от форума.',
	'BAN_TRIGGERED_BY_USER'	=> 'Потребителят с това потребителско име е изгонен от форума.',
	'BBCODE_GUIDE'			=> 'BBCode ръководство',
	'BCC'					=> 'BCC',
	'BIRTHDAYS'				=> 'Рождени дни',
	'BOARD_BAN_PERM'		=> 'Вие бяхте изгонени за <strong>постоянно</strong> от този форум.<br /><br />Моля, свържете се с %2$sадминистратора на форума%3$s за повече информация.',
	'BOARD_BAN_REASON'		=> 'Причина за изгонването: <strong>%s</strong>',
	'BOARD_BAN_TIME'		=> 'Изгонени сте от форума до <strong>%1$s</strong>.<br /><br />Моля, свържете се с %2$sадминистратора на форума%3$s за повече информация.',
	'BOARD_DISABLE'			=> 'Извиняваме се, но форумът в момента е недостъпен.',
	'BOARD_DISABLED'		=> 'В момента форумът не работи.',
	'BOARD_UNAVAILABLE'		=> 'Съжаляваме, но форумът е временно недостъпен, моля опитайте по-късно.',
	'BROWSING_FORUM'		=> 'Потребители, разглеждащи този форум: %1$s',
	'BROWSING_FORUM_GUESTS'	=> array(
		1	=> 'Потребители, разглеждащи този форум: %2$s и %1$d гост',
		2	=> 'Потребители, разглеждащи този форум: %2$s и %1$d госта',
	),
	'BUTTON_EDIT'			=> 'Промени',
	'BUTTON_FORUM_LOCKED'	=> 'Заключен',
	'BUTTON_NEW_TOPIC'		=> 'Нова тема',
	'BUTTON_PM'				=> 'ЛС',
	'BUTTON_PM_FORWARD'		=> 'Препрати',
	'BUTTON_PM_NEW'			=> 'Ново ЛС',
	'BUTTON_PM_REPLY'		=> 'Отговори',
	'BUTTON_PM_REPLY_ALL'	=> 'Отговори на всички',
	'BUTTON_POST_REPLY'		=> 'Отговори',
	'BUTTON_QUOTE'			=> 'Цитат',
	'BUTTON_TOPIC_LOCKED'	=> 'Заключена',
	'BYTES'					=> 'Байта',
	'BYTES_SHORT'			=> 'Б',

	'CANCEL'				=> 'Откажи',
	'CC_SENDER'				=> 'Изпрати копие от писмото до мен',
	'CHANGE'				=> 'Промени',
	'CHANGE_FONT_SIZE'		=> 'Промени размера на шрифта',
	'CHANGING_PREFERENCES'	=> 'Промяна настройкте на форума',
	'CHANGING_PROFILE'		=> 'Промяна настройките на профила',
	'CHARACTERS'			=> array(
		1	=> '%d символ',
		2	=> '%d символа',
	),
	'COLLAPSE_VIEW'			=> 'Сгъни изгледа',
	'CLOSE_WINDOW'			=> 'Затвори прозореца',
	'COLOUR_SWATCH'			=> 'Цветова палитра',
	'COLON'					=> ':',
	'COMMA_SEPARATOR'		=> ', ',	// Comma used to join lists into a single string, use localised comma if appropriate, eg: Ideographic or Arabic
	'CONFIRM'				=> 'Потвърди',
	'CONFIRM_CODE'			=> 'Код за потвърждаване',
	'CONFIRM_CODE_EXPLAIN'	=> 'Въведете кода, точно така, както е показан, без значение с малки или големи букви.',
	'CONFIRM_CODE_WRONG'	=> 'Въведеният код за потвърждение е неверен.',
	'CONFIRM_OPERATION'		=> 'Сигурен ли сте, че искате да изпълните тази операция?',
	'CONFIRM_AVATAR_DELETE' => 'Сигурни ли сте, че искате да изтриете този аватар??',
	'CONGRATULATIONS'		=> 'Поздравления за',
	'CONNECTION_FAILED'		=> 'Връзката е неуспешна.',
	'CONNECTION_SUCCESS'	=> 'Връзката е успешна!',
	'CONTACT'				=> 'Контакти',
	'CONTACT_USER'			=> 'Свържете се с %s',
	'CONTACT_US'			=> 'Свържете се с нас',
	'COOKIES_DELETED'		=> 'Всички бисквитки от форума бяха изтрити.',
	'CURRENT_TIME'			=> 'В момента е %s',

	'DAY'					=> 'Ден',
	'DAYS'					=> 'Дни',
	'DELETE'				=> 'Изтрий',
	'DELETE_ALL'			=> 'Изтрий всичко',
	'DELETE_COOKIES'		=> 'Изтрий всички бисквитки от форума',
	'DELETE_MARKED'			=> 'Изтрий маркираните',
	'DELETE_POST'			=> 'Изтрий мнението',
	'DELIMITER'				=> 'Разделител',
	'DESCENDING'			=> 'Низходящ',
	'DISABLED'				=> 'Забрани',
	'DISPLAY'				=> 'Покажи',
	'DISPLAY_GUESTS'		=> 'Покажи гостите',
	'DISPLAY_MESSAGES'		=> 'Покажи съобщенията от преди',
	'DISPLAY_POSTS'			=> 'Покажи мненията от преди',
	'DISPLAY_TOPICS'		=> 'Покажи темите от преди',
	'DOWNLOADED'			=> 'Свалени',
	'DOWNLOADING_FILE'		=> 'Сваляне на файла',
	'DOWNLOAD_COUNTS'		=> array(
		0	=> 'Все още не е свален',
		1	=> 'Свален %d път',
		2	=> 'Свален %d пъти',
	),

	'EDIT_POST'							=> 'Промени мнението',
	'ELLIPSIS'							=>	'…',
	'EMAIL'								=> 'Емейл', // Short form for EMAIL_ADDRESS
	'EMAIL_ADDRESS'						=> 'Емейл адрес',
	'EMAIL_INVALID_EMAIL'				=> 'Емейл адресът, който въведохте е невалиден.',
	'EMAIL_SMTP_ERROR_RESPONSE'			=> 'Възникна проблем при изпращането на емейл на <strong>Ред %1$s</strong>. Отговор: %2$s.',
	'EMPTY_SUBJECT'						=> 'Трябва да въведете заглавие, когато създавате нова тема.',
	'EMPTY_MESSAGE_SUBJECT'				=> 'Трябва да въведете заглавие на съобщението, когато изпращате ново съобщение.',
	'ENABLED'							=> 'Разреши',
	'ENCLOSURE'							=> 'Enclosure',
	'ENTER_USERNAME'					=> 'Въведете потребителско име',
	'ERR_CHANGING_DIRECTORY'			=> 'Неуспешна смяна на директорията.',
	'ERR_CONNECTING_SERVER'				=> 'Грешка при свързването със сървъра.',
	'ERR_JAB_AUTH'						=> 'Неуспешна ауторизация на Jabber сървъра.',
	'ERR_JAB_CONNECT'					=> 'Неуспешно свързване с Jabber сървъра.',
	'ERR_UNABLE_TO_LOGIN'				=> 'Грешно потребителско име или парола.',
	'ERR_UNWATCHING'					=> 'Възникна грешка при опита за спиране на абонамента.',
	'ERR_WATCHING'						=> 'Възникна грешка при опита за абониране.',
	'ERR_WRONG_PATH_TO_PHPBB'			=> 'Пътят към phpBB е грешен.',
	'ERROR'									=> 'Грешка',
	'EXPAND_VIEW'						=> 'Разгъни изгледа',
	'EXTENSION'							=> 'Разширения',
	'EXTENSION_DISABLED'				=> 'Разширението <strong>%s</strong> не е включено.',
	'EXTENSION_DISABLED_AFTER_POSTING'	=> 'Разширението <strong>%s</strong> беше изключено и няма да бъде показвано.',
	'EXTENSION_DOES_NOT_EXIST'			=> 'Разширението <strong>%s</strong> не съществува.',

	'FACEBOOK'				=> 'Facebook',
	'FAQ'					=> 'ЧЗВ',
	'FAQ_EXPLAIN'			=> 'Често Задавани Въпроси',
	'FILENAME'				=> 'Име на файла',
	'FILESIZE'				=> 'Размер на файла',
	'FILEDATE'				=> 'Дата на файла',
	'FILE_COMMENT'			=> 'Коментар на файла',
	'FILE_CONTENT_ERR'		=> 'Съдържанието на файла: %s не може да бъде прочетено',
	'FILE_JSON_DECODE_ERR'	=> 'Не може да се декодира json файла: %s',
	'FILE_NOT_FOUND'		=> 'Избраният файл не може да бъде намерен: %s',
	'FIND_USERNAME'			=> 'Намери потребител',
	'FOLDER'				=> 'Папка',
	'FORGOT_PASS'			=> 'Забравих си паролата',
	'FORM_INVALID'			=> 'Подадената форма е невалидна. Опитайте отново.',
	'FORUM'					=> 'Форум',
	'FORUMS'				=> 'Форуми',
	'FORUMS_MARKED'			=> 'Форумите бяха маркирани като прочетени.',
	'FORUM_CAT'				=> 'Категория на форума',
	'FORUM_INDEX'			=> 'Начало форум',
	'FORUM_LINK'			=> 'Връзка към форум',
	'FORUM_LOCATION'		=> 'Разположение на форума',
	'FORUM_LOCKED'			=> 'Форумът е заключен',
	'FORUM_RULES'			=> 'Правила на форума',
	'FORUM_RULES_LINK'		=> 'Моля, щракнете тук за да видите правилата на форума',
	'FROM'					=> 'от',
	'FSOCK_DISABLED'		=> 'Операцията не може да бъде изпълнена, защото <var>fsockopen</var> функцията е изключена и търсеният сървър не може да бъде намерен.',
	'FSOCK_TIMEOUT'			=> 'A timeout occurred while reading from the network stream.',

	'FTP_FSOCK_HOST'				=> 'FTP хост',
	'FTP_FSOCK_HOST_EXPLAIN'		=> 'FTP сървърът, на който се намира форумът.',
	'FTP_FSOCK_PASSWORD'			=> 'FTP парола',
	'FTP_FSOCK_PASSWORD_EXPLAIN'	=> 'Паролата на FTP потребителя.',
	'FTP_FSOCK_PORT'				=> 'FTP порт',
	'FTP_FSOCK_PORT_EXPLAIN'		=> 'Портът, използван за връзка със сървъра.',
	'FTP_FSOCK_ROOT_PATH'			=> 'Път към phpBB',
	'FTP_FSOCK_ROOT_PATH_EXPLAIN'	=> 'Пътят към коренната директория на phpBB форума.',
	'FTP_FSOCK_TIMEOUT'				=> 'FTP таймаут',
	'FTP_FSOCK_TIMEOUT_EXPLAIN'		=> 'Времето, в секунди, което системата ще изчаква за отговор от сървъра.',
	'FTP_FSOCK_USERNAME'			=> 'FTP потребител',
	'FTP_FSOCK_USERNAME_EXPLAIN'	=> 'Потребителското име, използвано за връзка със сървъра.',

	'FTP_HOST'					=> 'FTP хост',
	'FTP_HOST_EXPLAIN'			=> 'FTP сървърът, на който се намира форумът.',
	'FTP_PASSWORD'				=> 'FTP парола',
	'FTP_PASSWORD_EXPLAIN'		=> 'Паролата на FTP потребителя.',
	'FTP_PORT'					=> 'FTP порт',
	'FTP_PORT_EXPLAIN'			=> 'Портът, използван за връзка със сървъра.',
	'FTP_ROOT_PATH'				=> 'Път към phpBB',
	'FTP_ROOT_PATH_EXPLAIN'		=> 'Пътят към коренната директория на phpBB форума.',
	'FTP_TIMEOUT'				=> 'FTP таймаут',
	'FTP_TIMEOUT_EXPLAIN'		=> 'Времето, в секунди, което системата ще изчаква за отговор от сървъра.',
	'FTP_USERNAME'				=> 'FTP потребител',
	'FTP_USERNAME_EXPLAIN'		=> 'Потребителското име, използвано за връзка със сървъра.',

	'GENERAL_ERROR'				=> 'Обща грешка',
	'GB'						=> 'ГБ',
	'GIB'						=> 'ГБ',
	'GO'						=> 'Go',
	'GOOGLEPLUS'				=> 'Google+',
	'GOTO_FIRST_POST'			=> 'Отиди на първото мнение',
	'GOTO_LAST_POST'			=> 'Отиди на последното мнение',
	'GOTO_PAGE'					=> 'Отиди на страница',
	'GROUP'						=> 'Група',
	'GROUPS'					=> 'Групи',
	'GROUP_ERR_TYPE'			=> 'Избрана е неподходяща група.',
	'GROUP_ERR_USERNAME'		=> 'Не е избрано име на групата.',
	'GROUP_ERR_USER_LONG'		=> 'Имената на групите не могат да превишават 60 символа. Избраново име на групата е твърде дълго.',
	'GUEST'						=> 'Гост',
	'GUEST_USERS_ONLINE'		=> array(
		1	=> 'Има %d гост на линия',
		2	=> 'Има %d госта на линия',
	),
	'GUEST_USERS_TOTAL'			=> array(
		1	=> '%d гост',
		2	=> '%d госта',
	),
	'G_ADMINISTRATORS'			=> 'Администратори',
	'G_BOTS'					=> 'Ботове',
	'G_GUESTS'					=> 'Гости',
	'G_REGISTERED'				=> 'Регистрирани потребители',
	'G_REGISTERED_COPPA'		=> 'Регистрирани COPPA потребители',
	'G_GLOBAL_MODERATORS'		=> 'Глобални модератори',
	'G_NEWLY_REGISTERED'		=> 'Новорегистрирани потребители',

	'HIDDEN_USERS_ONLINE'		=> array(
		1	=> '%d скрит потребител',
		2	=> '%d скрити потребители',
	),
	'HIDDEN_USERS_TOTAL'		=> array(
		1	=> '%d скрит',
		2	=> '%d скрити',
	),
	'HIDE_GUESTS'					=> 'Скрий гостите',
	'HIDE_ME'						=> 'Скрий онлайн статуса ми за тази сесия',
	'HOURS'							=> 'Часове',
	'HOME'							=> 'Начало',

	'ICQ'						=> 'ICQ',
	'IF'						=> 'Ако',
	'IMAGE'						=> 'Изображение',
	'IMAGE_FILETYPE_INVALID'	=> 'Изображение тип %d за mimetype %s не се поддържа.',
	'IMAGE_FILETYPE_MISMATCH'	=> 'Несъответствие между типа на изображението: очаквано разширение %1$s, но разширение %2$s е получено.',
	'IN'						=> 'в',
	'INDEX'						=> 'Начало',
	'INFORMATION'				=> 'Информация',
	'INSECURE_REDIRECT'			=> 'Опит за пренасочване към потенциално опасен адрес.',
	'INTERESTS'					=> 'Интереси',
	'INVALID_DIGEST_CHALLENGE'	=> 'Невалидно предизвикателсво.',
	'INVALID_EMAIL_LOG'			=> '<strong>%s</strong> може би е грешен емейл адрес?',
	'INVALID_PLURAL_RULE'		=> 'Избраното множествено правило е грешно. Валидни стойности са цели числа между 0 и 15.',
	'IP'						=> 'IP',
	'IP_BLACKLISTED'			=> 'Вашият IP адрес %1$s е блокиран защото е в черния списък. За повече информация, моля посетете <a href="%2$s">%2$s</a>.',

	'JABBER'				=> 'Jabber',
	'JOINED'				=> 'Регистриран',
	'JUMP_PAGE'				=> 'Моля, въведете страницата, на която искате да отидете',
	'JUMP_TO'				=> 'Отиди на',
	'JUMP_TO_PAGE'			=> 'Отиди на страница',
	'JUMP_TO_PAGE_CLICK'	=> 'Кликнете за да преминете на страница…',

	'KB'					=> 'KБ',
	'KIB'					=> 'KБ',

	'LAST_POST'							=> 'Последно мнение',
	'LAST_UPDATED'						=> 'Последно обновена',
	'LAST_VISIT'						=> 'Последно посещение',
	'LDAP_NO_LDAP_EXTENSION'			=> 'LDAP разширението не е налично.',
	'LDAP_NO_SERVER_CONNECTION'			=> 'Неуспешно свързване с LDAP сървъра.',
	'LDAP_SEARCH_FAILED'				=> 'Възникна прешка при търсенето в LDAP директорията.',
	'LEGEND'							=> 'Легенда',
	'LIVE_SEARCHES_NOT_ALLOWED'			=> 'Live searches are not allowed.',
	'LOADING'							=> 'Зареждане',
	'LOCATION'							=> 'Местоположение',
	'LOCK_POST'							=> 'Заключи мнението',
	'LOCK_POST_EXPLAIN'					=> 'Забрани промяната на мнението',
	'LOCK_TOPIC'						=> 'Заключи темата',
	'LOGIN'								=> 'Влез',
	'LOGIN_CHECK_PM'					=> 'Влезте, за да видите личните си съобщения.',
	'LOGIN_CONFIRMATION'				=> 'Потвърждение за вход',
	'LOGIN_CONFIRM_EXPLAIN'				=> 'To prevent brute forcing accounts the board requires you to enter a confirmation code after a maximum amount of failed logins. The code is displayed in the image you should see below. If you are visually impaired or cannot otherwise read this code please contact the %sBoard Administrator%s.', // unused
	'LOGIN_ERROR_ATTEMPTS'				=> 'Превишихте броя на позволените опити за вход. В допълнение към потребителското Ви име и парола ще трябва да въведете и показания долу код.',
	'LOGIN_ERROR_EXTERNAL_AUTH_APACHE'	=> 'You have not been authenticated by Apache.',
	'LOGIN_ERROR_OAUTH_SERVICE_DOES_NOT_EXIST'	=> 'A non-existant OAuth service has been requested.',
	'LOGIN_ERROR_PASSWORD'				=> 'Въведохте неправилна парола. Моля, проверете паролата и опитайте отново. Ако продължите да имате проблеми, моля свържете се с %sBoard Administrator%s.',
	'LOGIN_ERROR_PASSWORD_CONVERT'		=> 'It was not possible to convert your password when updating this bulletin board’s software. Please %srequest a new password%s. If you continue to have problems please contact the %sBoard Administrator%s.',
	'LOGIN_ERROR_USERNAME'				=> 'Въведохте неправилно потребителско име. Моля, проверете потребителското име и опитайте отново. Ако продължите да имате проблеми, моля свържете се с %sадминистратора на форума%s.',
	'LOGIN_FORUM'						=> 'За да разглеждате и публикувате мнения в този форум трябва да въвдетете парола.',
	'LOGIN_INFO'						=> 'За да влезете, трябва да сте регистриран. Регистрацията отнема само няколко минути, но Ви дава разширени възможности. Администраторите на форума могат също така да разрешат допълнителни дейтвия на регистрираните потребители. Преди да се регистрирате, моля уверете се, че сте се запознали с правилата на форума.',
	'LOGIN_VIEWFORUM'					=> 'За да разглеждате този форум трябва да сте регистриран и да сте влезли в профила си.',
	'LOGIN_EXPLAIN_EDIT'				=> 'За да променяте мнения в този форум трябва да сте регистриран и да сте влезли в профила си.',
	'LOGIN_EXPLAIN_VIEWONLINE'			=> 'За да видите листа с потребителите на линия трябва да сте регистриран и да сте влезли в профила си.',
	'LOGIN_REQUIRED'					=> 'Трябва да сте влезли в профила си за да изпълните това действие.',
	'LOGOUT'							=> 'Излез',
	'LOGOUT_USER'						=> 'Излез [ %s ]',
	'LOG_ME_IN'							=> 'Запомни ме',

	'MAIN'					=> 'Главна',
	'MARK'					=> 'Маркирай',
	'MARK_ALL'				=> 'Маркирай всички',
	'MARK_ALL_READ'			=> 'Маркирай всички като прочетени',
	'MARK_FORUMS_READ'		=> 'Маркирай форумите като прочетени',
	'MARK_READ'				=> 'Маркирай като прочетено',
	'MARK_SUBFORUMS_READ'	=> 'Маркирай подфорумите като прочетени',
	'MB'					=> 'МБ',
	'MIB'					=> 'MБ',
	'MCP'					=> 'Модераторски панел',
	'MCP_SHORT'				=> 'МКП',
	'MEMBERLIST'			=> 'Потребители',
	'MEMBERLIST_EXPLAIN'	=> 'Разгледай пълният списък на потребителите',
	'MERGE'					=> 'Слей',
	'MERGE_POSTS'			=> 'Премести мненията',
	'MERGE_TOPIC'			=> 'Слей с тема',
	'MESSAGE'				=> 'Съобщение',
	'MESSAGES'				=> 'Съобщения',
	'MESSAGES_COUNT'		=> array(
		1	=> '%d съобщение',
		2	=> '%d съобщения',
	),
	'MESSAGE_BODY'			=> 'Текст на съобщението',
	'MINUTES'				=> 'Минути',
	'MODERATE'				=> 'Модерирай',
	'MODERATOR'				=> 'Модератор',
	'MODERATORS'			=> 'Модератори',
	'MODULE_NOT_ACCESS'		=> 'Модулът не е достъпен',
	'MODULE_NOT_FIND'		=> '%s модулът не може да бъде намерен',
	'MODULE_FILE_INCORRECT_CLASS'	=> 'Module file %s does not contain correct class [%s]',
	'MONTH'					=> 'Месец',
	'MOVE'					=> 'Премести',

	'NA'						=> 'N/A',
	'NEWEST_USER'				=> 'Последно регистриран потребител <strong>%s</strong>',
	'NEW_MESSAGE'				=> 'Ново съобщение',
	'NEW_MESSAGES'				=> 'Нови съобщения',
	'NEW_POST'					=> 'New post',	// Not used anymore
	'NEW_POSTS'					=> 'New posts',	// Not used anymore
	'NEXT'						=> 'Следваща',		// Used in pagination
	'NEXT_STEP'					=> 'Напред',
	'NEVER'						=> 'Никога',
	'NO'						=> 'Не',
	'NO_NOTIFICATIONS'			=> 'Нямате нови известия',
	'NOT_ALLOWED_MANAGE_GROUP'	=> 'Нямате права да управлявате тази група.',
	'NOT_AUTHORISED'			=> 'Нямате права на достъп до този раздел.',
	'NOT_WATCHING_FORUM'		=> 'Вече не сте абониран за този форум.',
	'NOT_WATCHING_TOPIC'		=> 'Вече не сте абониран за тази тема.',
	'NOTIFICATIONS'				=> 'Известия',
	// This applies for NOTIFICATION_BOOKMARK and NOTIFICATION_POST.
	// %1$s will return a list of users that's concatenated using "," and "and" - see STRING_LIST
	// Once the user count reaches 5 users or more, the list is trimmed using NOTIFICATION_X_OTHERS
	// Once the user count reaches 20 users or more, the list is trimmed using NOTIFICATION_MANY_OTHERS
	// Examples:
	// A replied...
	// A and B replied...
	// A, B and C replied...
	// A, B, C and 2 others replied...
	// A, B, C and others replied...
	'NOTIFICATION_BOOKMARK'				=> array(
		1	=> '%1$s <strong>отговори</strong> в тема, за която сте абониран:',
	),
	'NOTIFICATION_FORUM'				=> '<em>Форум:</em> %1$s',
	'NOTIFICATION_GROUP_REQUEST'		=> '%1$s желае да се присъедини към групата %2$s.',
	'NOTIFICATION_GROUP_REQUEST_APPROVED'	=> 'Изкането за присъединяване към групата %1$s е <strong>одобрено</strong>.',
	'NOTIFICATION_PM'					=> '<strong>Лично съобщение</strong> от %1$s:',
	'NOTIFICATION_POST'					=> array(
		1	=> '<strong>Отговор</strong> от %1$s в тема:',
	),
	'NOTIFICATION_POST_APPROVED'		=> '<strong>Мнението е одобрени</strong>:',
	'NOTIFICATION_POST_DISAPPROVED'		=> '<strong>Мнението не е одобрено</strong>:',
	'NOTIFICATION_POST_IN_QUEUE'		=> '%1$s иска <strong>одобрение на мнението</strong>:',
	'NOTIFICATION_QUOTE'				=> array(
		1	=> '%1$s <strong>Ви цитира</strong> в:',
	),
	'NOTIFICATION_REFERENCE'			=> '"%1$s"',
	'NOTIFICATION_REASON'				=> '<em>Причина:</em> %1$s.',
	'NOTIFICATION_REPORT_PM'			=> '<strong>Лично съобщение докладвано</strong> от %1$s:',
	'NOTIFICATION_REPORT_POST'			=> '<strong>Мнение докладвано</strong> от %1$s:',
	'NOTIFICATION_REPORT_CLOSED'		=> '<strong>Затворен доклад</strong> от %1$s за:',
	'NOTIFICATION_TOPIC'				=> '<strong>Нова тема</strong> от %1$s:',
	'NOTIFICATION_TOPIC_APPROVED'		=> '<strong>Одобрена тема</strong>:',
	'NOTIFICATION_TOPIC_DISAPPROVED'	=> '<strong>Неодобрена тема</strong>:',
	'NOTIFICATION_TOPIC_IN_QUEUE'		=> '%1$s иска <strong>одобрение на тема</strong>',
	'NOTIFICATION_TYPE_NOT_EXIST'		=> 'The notification type "%s" is missing from the file system.',
	'NOTIFICATION_ADMIN_ACTIVATE_USER'	=> 'Новорегистрираният потребител: “%1$s” <strong>изисква активация</strong>',
	// Used in conjuction with NOTIFICATION_BOOKMARK and NOTIFICATION_POST.
	'NOTIFICATION_MANY_OTHERS'			=> 'други',
	'NOTIFICATION_X_OTHERS'				=> array(
		2	=> '%d други',
	),
	'NOTIFY_ADMIN'				=> 'Моля, уведомете администратора или собственика на сайта.',
	'NOTIFY_ADMIN_EMAIL'		=> 'Моля, уведомете администратора или собственика на сайта: <a href="mailto:%1$s">%1$s</a>',
	'NO_ACCESS_ATTACHMENT'		=> 'Нямате права да достъпите този файл.',
	'NO_ACTION'					=> 'Няма избрано действие.',
	'NO_ADMINISTRATORS'			=> 'Няма администратори.',
	'NO_AUTH_ADMIN'				=> 'Достъпът до Административния Контролен Панел не е разрешен, тъй като нямате административни привилегии.',
	'NO_AUTH_ADMIN_USER_DIFFER'	=> 'Не можете да влезете като различен потребител.',
	'NO_AUTH_OPERATION'			=> 'Нямате необходимите права за да изпълните тази операция.',
	'NO_AVATARS'				=> 'В момента няма аватари',
	'NO_CONNECT_TO_SMTP_HOST'	=> 'Не може да се свържем с smtp хоста : %1$s : %2$s',
	'NO_BIRTHDAYS'				=> 'Днес никой не празнува рожден ден',
	'NO_EMAIL_MESSAGE'			=> 'Емейл съобщението беше празно.',
	'NO_EMAIL_RESPONSE_CODE'	=> 'Could not get mail server response codes.',
	'NO_EMAIL_SUBJECT'			=> 'No email subject specified.',
	'NO_FORUM'					=> 'Форумът, който избрахте не съществува.',
	'NO_FORUMS'					=> 'Няма създадени форуми.',
	'NO_GROUP'					=> 'Дадената потребителска група не съществува.',
	'NO_GROUP_MEMBERS'			=> 'Тази група няма членове.',
	'NO_IPS_DEFINED'			=> 'No IP addresses or hostnames defined',
	'NO_MEMBERS'				=> 'Няма намерени потребители по търсените критерии.',
	'NO_MESSAGES'				=> 'Няма съобщения',
	'NO_MODE'					=> 'Не е избран режим.',
	'NO_MODERATORS'				=> 'Няма модератори.',
	'NO_NEW_MESSAGES'			=> 'Няма нови съобщения',
	'NO_NEW_POSTS'				=> 'No new posts',	// Not used anymore
	'NO_ONLINE_USERS'			=> 'Няма регистрирани потребители',
	'NO_POSTS'					=> 'Няма мнения',
	'NO_POSTS_TIME_FRAME'		=> 'Няма мнения в тази тема за избрания период.',
	'NO_FEED_ENABLED'			=> 'Feeds are not available on this board.',
	'NO_FEED'					=> 'The requested feed is not available.',
	'NO_STYLE_DATA'				=> 'Няма данни за стила',
	'NO_SUBJECT'				=> 'Няма заглавие',								// Used for posts having no subject defined but displayed within management pages.
	'NO_SUCH_SEARCH_MODULE'		=> 'The specified search backend doesn’t exist.',
	'NO_SUPPORTED_AUTH_METHODS'	=> 'No supported authentication methods.',
	'NO_TOPIC'					=> 'Темата не съществува.',
	'NO_TOPIC_FORUM'			=> 'Темата или форумът вече не съществуват.',
	'NO_TOPICS'					=> 'Няма теми или мнения в този форум.',
	'NO_TOPICS_TIME_FRAME'		=> 'Няма теми в този форум за избрания период.',
	'NO_UNREAD_POSTS'			=> 'Няма непрочетени мнения',
	'NO_UPLOAD_FORM_FOUND'		=> 'Upload initiated but no valid file upload form found.',
	'NO_USER'					=> 'Даденият потребител не съществува.',
	'NO_USERS'					=> 'Дадените потребители не съществуват.',
	'NO_USER_SPECIFIED'			=> 'Не е въведено потребителско име.',

	// Nullar/Singular/Plural language entry. The key numbers define the number range in which a certain grammatical expression is valid.
	'NUM_ATTACHMENTS'		=> array(
		1	=> '%d прикачен файл',
		2	=> '%d прикачени файлa',
	),
	'NUM_POSTS_IN_QUEUE'		=> array(
		0			=> 'Няма мнения в опашката',		// 0
		1			=> '1 мнение в опашката',		// 1
		2			=> '%d мнения в опашката',		// 2+
	),

	'OCCUPATION'				=> 'Професия',
	'OFFLINE'					=> 'Извън линия',
	'ONLINE'					=> 'На линия',
	'ONLINE_BUDDIES'			=> 'Приятели на линия',
	// "... :: x registered and y hidden"
	'ONLINE_USERS_TOTAL'		=> array(
		1	=> 'В момента има <strong>%1$d</strong> потребител на линия :: %2$s и %3$s',
		2	=> 'В момента има <strong>%1$d</strong> потребителя на линия :: %2$s и %3$s',
	),
	// "... :: x registered, y hidden and z guests"
	'ONLINE_USERS_TOTAL_GUESTS'	=> array(
		1	=> 'В момента има <strong>%1$d</strong> потребител на линия :: %2$s, %3$s и %4$s',
		2	=> 'В момента има <strong>%1$d</strong> потребителя на линия :: %2$s, %3$s и %4$s',
	),
	'OPTIONS'					=> 'Опции',

	'PAGE_OF'				=> 'Страница <strong>%1$d</strong> от <strong>%2$d</strong>',
	'PAGE_TITLE_NUMBER'		=> 'Страница %s',
	'PASSWORD'				=> 'Парола',
	'PIXEL'					=> 'px',
	'PIXELS'				=> array(
		1	=> '%d пиксел',
		2	=> '%d пиксела',
	),
	'PLAY_QUICKTIME_FILE'	=> 'Play Quicktime file',
	'PLEASE_WAIT'			=> 'Моля изчакайте.',
	'PM'					=> 'ЛС',
	'PM_REPORTED'			=> 'Щракнете за да видите доклада',
	'POSTING_MESSAGE'		=> 'Публикуване на съобщение в %s',
	'POSTING_PRIVATE_MESSAGE'	=> 'Създаване на лично съобщение',
	'POST'					=> 'Мнение',
	'POST_ANNOUNCEMENT'		=> 'Важно съобщение',
	'POST_STICKY'			=> 'Закачена тема',
	'POSTED'				=> 'Публикувано',
	'POSTED_IN_FORUM'		=> 'в',
	'POSTED_ON_DATE'		=> 'на',
	'POSTS'					=> 'Мнения',
	'POSTS_UNAPPROVED'		=> 'Поне едно мнение в тази тема не е било одобрено.',
	'POSTS_UNAPPROVED_FORUM'=> 'Поне едно мнение в този форум не е било одобрено.',
	'POST_BY_AUTHOR'		=> 'от',
	'POST_BY_FOE'			=> '<strong>%1$s</strong>, който е в списъка Ви с врагове публикува това мнение.',
	'POST_DISPLAY'			=> '%1$sПокажи това мнение%2$s.',
	'POST_DAY'				=> '%.2f мнения на ден',
	'POST_DELETED_ACTION'	=> 'Изтрито мнение:',
	'POST_DELETED'			=> 'Това мнение беше изтрито.',
	'POST_DELETED_BY'		=> '<strong>%2$s</strong> изтри мнение от <strong>%1$s</strong> на %3$s.',
	'POST_DELETED_BY_REASON'=> '<strong>%2$s</strong> изтри мнение от <strong>%1$s</strong> на %3$s поради следната причина: %4$s',
	'POST_DETAILS'			=> 'Детайли на мнението',
	'POST_NEW_TOPIC'		=> 'Създай нова тема',
	'POST_PCT'				=> '%.2f%% от всички мнения',
	'POST_PCT_ACTIVE'		=> '%.2f%% от мненията на потребителя',
	'POST_PCT_ACTIVE_OWN'	=> '%.2f%% от вашите мнения',
	'POST_REPLY'			=> 'Публикувай отговор',
	'POST_REPORTED'			=> 'Щракнете за да видите доклада',
	'POST_SUBJECT'			=> 'Заглавие',
	'POST_TIME'				=> 'Дата/час',
	'POST_TOPIC'			=> 'Публикувай нова тема',
	'POST_UNAPPROVED_ACTION'	=> 'Мнението изчаква одобрение:',
	'POST_UNAPPROVED'		=> 'Това мнение изчаква одобрение.',
	'POWERED_BY'			=> 'Powered by %s',
	'PREVIEW'				=> 'Преглед',
	'PREVIOUS'				=> 'Предишна',		// Used in pagination
	'PREVIOUS_STEP'			=> 'Назад',
	'PRIVACY'				=> 'Защита на личните данни',
	'PRIVATE_MESSAGE'		=> 'Лично съобщение',
	'PRIVATE_MESSAGES'		=> 'Лични съобщения',
	'PRIVATE_MESSAGING'		=> 'Лични съобщения',
	'PROFILE'				=> 'Потребителски панел',

	'QUICK_LINKS'			=> 'Бързи връзки',

	'RANK'						=> 'Ранг',
	'READING_FORUM'				=> 'Разглежда теми в %s',
	'READING_GLOBAL_ANNOUNCE'	=> 'Чете глобалните съобщения',
	'READING_LINK'				=> 'Следва форум връзка %s',
	'READING_TOPIC'				=> 'Чете тема в %s',
	'READ_PROFILE'				=> 'Профил',
	'REASON'					=> 'Причина',
	'RECORD_ONLINE_USERS'		=> 'Най-много потребители на линия <strong>%1$s</strong> е имало на %2$s',
	'REDIRECT'					=> 'Пренасочване',
	'REDIRECTS'					=> 'Общо пренасочвания',
	'REGISTER'					=> 'Регистрация',
	'REGISTERED_USERS'			=> 'Регистрирани потребители:',
	// "... and 2 hidden users online"
	'REG_USERS_ONLINE'			=> array(
		1	=> 'Има %1$d регистриран потребител и %2$s на линия',
		2	=> 'Има %1$d регистрирани потребители и %2$s на линия',
	),
	'REG_USERS_TOTAL'			=> array(
		1	=> '%d регистриран',
		2	=> '%d регистрирани',
	),
	'REMOVE'					=> 'Изтрий',
	'REMOVE_INSTALL'			=> 'Моля, изтрийте, преместете или преименувайте директорията install преди да използвате форума. Докато директорията съществува, само Административният Контролен Панел (АКП) ще бъде достъпен.',
	'REPLIES'					=> 'Отговори',
	'REPLY_WITH_QUOTE'			=> 'Отговори с цитат',
	'REPLYING_GLOBAL_ANNOUNCE'	=> 'Отговаря на глобално съобщение',
	'REPLYING_MESSAGE'			=> 'Отговаря на съобщение в %s',
	'REPORT_BY'					=> 'Доклад от',
	'REPORT_POST'				=> 'Докладвай това мнение',
	'REPORTING_POST'			=> 'Докладва мнение',
	'RESEND_ACTIVATION'			=> 'Изпрати отново активационния емейл',
	'RESET'						=> 'Изчисти',
	'RESTORE_PERMISSIONS'		=> 'Възстанови правата',
	'RETURN_INDEX'				=> '%sВърни се в началото на форума%s',
	'RETURN_FORUM'				=> '%sВърни се в последно посетения форум%s',
	'RETURN_PAGE'				=> '%sВърни се на предишната страница%s',
	'RETURN_TOPIC'				=> '%sВърни се на последно посетената тема%s',
	'RETURN_TO'					=> 'Върни се в “%s”',
	'RETURN_TO_INDEX'			=> 'Върни се в началото на форума',
	'FEED'						=> 'Хранилка',
	'FEED_NEWS'					=> 'Новини',
	'FEED_TOPICS_ACTIVE'		=> 'Активни теми',
	'FEED_TOPICS_NEW'			=> 'Нови теми',
	'RULES_ATTACH_CAN'			=> 'Вие <strong>можете</strong> да прикачвате файлове в този форум',
	'RULES_ATTACH_CANNOT'		=> 'Вие <strong>не можете</strong> да прикачвате файлове в този форум',
	'RULES_DELETE_CAN'			=> 'Вие <strong>можете</strong> да триете мнения в този форум',
	'RULES_DELETE_CANNOT'		=> 'Вие <strong>не можете</strong> да триете мнения в този форум',
	'RULES_DOWNLOAD_CAN'		=> 'Вие <strong>можете</strong> да сваляте прикачени файлове в този форум',
	'RULES_DOWNLOAD_CANNOT'		=> 'Вие <strong>не можете</strong> да сваляте прикачени файлове в този форум',
	'RULES_EDIT_CAN'			=> 'Вие <strong>можете</strong> да променяте собствените си мнения в този форум',
	'RULES_EDIT_CANNOT'			=> 'Вие <strong>не можете</strong> да променяте собствените си мнения в този форум',
	'RULES_LOCK_CAN'			=> 'Вие <strong>можете</strong> да заключвате собствените си теми в този форум',
	'RULES_LOCK_CANNOT'			=> 'Вие <strong>не можете</strong> да заключвате собствените си теми в този форум',
	'RULES_POST_CAN'			=> 'Вие <strong>можете</strong> да публикувате теми в този форум',
	'RULES_POST_CANNOT'			=> 'Вие <strong>не можете</strong> да публикувате теми в този форум',
	'RULES_REPLY_CAN'			=> 'Вие <strong>можете</strong> да отговаряте на теми в този форум',
	'RULES_REPLY_CANNOT'		=> 'Вие <strong>не можете</strong> да отговаряте на теми в този форум',
	'RULES_VOTE_CAN'			=> 'Вие <strong>можете</strong> да гласувате в анкети в този форум',
	'RULES_VOTE_CANNOT'			=> 'Вие <strong>не можете</strong> да гласувате в анкети в този форум',

	'SEARCH'					=> 'Търсене',
	'SEARCH_MINI'				=> 'Търсене…',
	'SEARCH_ADV'				=> 'Разширено търсене',
	'SEARCH_ADV_EXPLAIN'		=> 'Вижте опциите на разширеното търсене',
	'SEARCH_KEYWORDS'			=> 'Търси за ключови думи',
	'SEARCHING_FORUMS'			=> 'Търсене във форуми',
	'SEARCH_ACTIVE_TOPICS'		=> 'Виж активните теми',
	'SEARCH_FOR'				=> 'Търси за',
	'SEARCH_FORUM'				=> 'Търси в този форум…',
	'SEARCH_NEW'				=> 'Виж новите мнения',
	'SEARCH_POSTS_BY'			=> 'Търси мнения от',
	'SEARCH_SELF'				=> 'Виж собствените си мнения',
	'SEARCH_TOPIC'				=> 'Търси в тази тема…',
	'SEARCH_UNANSWERED'			=> 'Виж темите без отговор',
	'SEARCH_UNREAD'				=> 'Виж непрочетените мнения',
	'SEARCH_USER_POSTS'			=> 'Търси в потребителските мнения',
	'SECONDS'					=> 'Секунди',
	'SEE_ALL'					=> 'Виж всички',
	'SELECT'					=> 'Избери',
	'SELECT_ALL_CODE'			=> 'Избери всички',
	'SELECT_DESTINATION_FORUM'	=> 'Моля, изберете форум дестинация',
	'SELECT_FORUM'				=> 'Изберете форум',
	'SEND_EMAIL'				=> 'Изпрати емейл',				// Used for submit buttons
	'SEND_EMAIL_USER'			=> 'Изпрати емейл до %s',
	'SEND_PRIVATE_MESSAGE'		=> 'Изпрати лично съобщение',
	'SETTINGS'					=> 'Настройки',
	'SIGNATURE'					=> 'Подпис',
	'SKIP'						=> 'Премини към съдържанието',
	'SKYPE'						=> 'Skype',
	'SMTP_NO_AUTH_SUPPORT'		=> 'SMTP server does not support authentication.',
	'SORRY_AUTH_READ'			=> 'Нямате права да четете този форум.',
	'SORRY_AUTH_VIEW_ATTACH'	=> 'Нямате права да свалите този прикачен файл.',
	'SORT_BY'					=> 'Сортирай по',
	'SORT_JOINED'				=> 'Дата на регистрация',
	'SORT_LOCATION'				=> 'Местоположение',
	'SORT_RANK'					=> 'Ранг',
	'SORT_POSTS'				=> 'Мнения',
	'SORT_TOPIC_TITLE'			=> 'Заглавие на темата',
	'SORT_USERNAME'				=> 'Потребителско име',
	'SPLIT_TOPIC'				=> 'Раздели темата',
	'SQL_ERROR_OCCURRED'		=> 'An SQL error occurred while fetching this page. Please contact the %sBoard Administrator%s if this problem persists.',
	'STATISTICS'				=> 'Статистики',
	'START_WATCHING_FORUM'		=> 'Абониране за форума',
	'START_WATCHING_TOPIC'		=> 'Абониране за темата',
	'STOP_WATCHING_FORUM'		=> 'Отписване от форума',
	'STOP_WATCHING_TOPIC'		=> 'Отписване от темата',
	'STRING_LIST_MULTI'			=> '%1$s, и %2$s',
	'STRING_LIST_SIMPLE'		=> '%1$s и %2$s',
	'SUBFORUM'					=> 'Подфорум',
	'SUBFORUMS'					=> 'Подфоруми',
	'SUBJECT'					=> 'Заглавие',
	'SUBMIT'					=> 'Прати',

	'TB'				=> 'TБ',
	'TERMS_USE'			=> 'Условия за ползване',
	'TEST_CONNECTION'	=> 'Тествай връзката',
	'THE_TEAM'			=> 'Екипът',
	'TIB'				=> 'TiB',
	'TIME'				=> 'Време',
	'TIMEOUT_PROCESSING_REQ'			=> 'Времето за изпълнение на заявката изтече.',

	'TOO_LARGE'						=> 'Стойността, която въведохте е твърде голяма.',
	'TOO_LARGE_MAX_RECIPIENTS'		=> 'Стойността на настройката за <strong>Максимален брой позволени получатели на едно лично съобщение</strong> е твърде голяма.',

	'TOO_LONG'						=> 'Стойността, която въведохте е твърде дълга.',

	'TOO_LONG_CONFIRM_CODE'			=> 'Кодът за потвърждение, който въведохте е твърде дълъг.',
	'TOO_LONG_DATEFORMAT'			=> 'Форматът на датата, който въведохте е твърде дълъг.',
	'TOO_LONG_JABBER'				=> 'Jabber потребителското име, което въведохте е твърде дълго.',
	'TOO_LONG_NEW_PASSWORD'			=> 'Паролата, която въведохте е твърде дълга.',
	'TOO_LONG_PASSWORD_CONFIRM'		=> 'Потвърждението на паролата, което въведохте е твърде дълго.',
	'TOO_LONG_USER_PASSWORD'		=> 'Паролата, която въведохте е твърде дълга.',
	'TOO_LONG_USERNAME'				=> 'Потребителското име, което въведохте е твърде дълго.',
	'TOO_LONG_EMAIL'				=> 'Емейл адресът, който въведохте е твърде дълъг.',

	'TOO_MANY_VOTE_OPTIONS'			=> 'Опитвате се да гласувате за твърде много отговори.',

	'TOO_SHORT'						=> 'Стойността, която въведохте е твърде къса.',

	'TOO_SHORT_CONFIRM_CODE'		=> 'Кодът за потвърждение, който въведохте е твърде къс.',
	'TOO_SHORT_DATEFORMAT'			=> 'Форматът на датата, който въведохте е твърде къс.',
	'TOO_SHORT_JABBER'				=> 'Jabber потребителското име, което въведохте е твърде късо.',
	'TOO_SHORT_NEW_PASSWORD'		=> 'Паролата, която въведохте е твърде къса.',
	'TOO_SHORT_PASSWORD_CONFIRM'	=> 'Потвърждението на паролата, което въведохте е твърде късо.',
	'TOO_SHORT_USER_PASSWORD'		=> 'Паролата, която въведохте е твърде къса.',
	'TOO_SHORT_USERNAME'			=> 'Потребителското име, което въведохте е твърде късо.',
	'TOO_SHORT_EMAIL'				=> 'Емейл адресът, който въведохте е твърде къс.',
	'TOO_SHORT_EMAIL_CONFIRM'		=> 'Потвърждението на емейл адресът, който въведохте е твърде късо.',
	'TOO_SMALL'						=> 'Стойността, която въведохте е твърде малка.',
	'TOO_SMALL_MAX_RECIPIENTS'		=> 'Стойността на настройката за <strong>Максимален брой позволени получатели на едно лично съобщение</strong> е твърде малка.',

	'TOPIC'				=> 'Тема',
	'TOPICS'			=> 'Теми',
	'TOPICS_UNAPPROVED'	=> 'Поне една тема в този форум не е одобрена.',
	'TOPIC_ICON'		=> 'Икона на темата',
	'TOPIC_LOCKED'		=> 'Тази тема е заключена, не можете да променяте мнения или да публикувате нови отговори.',
	'TOPIC_LOCKED_SHORT'=> 'Заключена тема',
	'TOPIC_MOVED'		=> 'Преместена тема',
	'TOPIC_REVIEW'		=> 'Преглед на темата',
	'TOPIC_TITLE'		=> 'Заглавие на темата',
	'TOPIC_UNAPPROVED'	=> 'Тази тема не беше одобрена.',
	'TOPIC_DELETED'		=> 'Тази тема беше изтрита.',
	'TOTAL_ATTACHMENTS'	=> 'Прикачен(и) файл(ове)',
	'TOTAL_LOGS'		=> array(
		1	=> '%d лог',
		2	=> '%d логове',
	),
	'TOTAL_PMS'		=> array(
		1	=> '%d лично съобщение общо',
		2	=> '%d лични съобщения общо',
	),
	'TOPIC_POLL'		=> 'Темата има анкета.',
	'TOTAL_POSTS'		=> 'Общо мнения',
	'TOTAL_POSTS_COUNT'	=> array(
		2	=> 'Общо мнения <strong>%d</strong>',
	),
	'TOPIC_REPORTED'	=> 'Темата беше докладвана',
	'TOTAL_TOPICS'		=> array(
		2	=> 'Общо теми <strong>%d</strong>',
	),
	'TOTAL_USERS'		=> array(
		2	=> 'Общо потребители <strong>%d</strong>',
	),
	'TRACKED_PHP_ERROR'	=> 'Регистрирани PHP грешки: %s',
	'TWITTER'			=> 'Twitter',

	'UNABLE_GET_IMAGE_SIZE'	=> 'Не успяхме да определим размерите на изображението. Моля, уверете се, че адресът, който сте въвели е правилен.',
	'UNABLE_TO_DELIVER_FILE'=> 'Не успяхме да доставим файла.',
	'UNKNOWN_BROWSER'		=> 'Неизвестен браузър',
	'UNMARK_ALL'			=> 'Размаркирай всички',
	'UNREAD_MESSAGES'		=> 'Непрочетени съобщения',
	'UNREAD_POST'			=> 'Непрочетено мнение',
	'UNREAD_POSTS'			=> 'Непрочетени мнения',
	'UNWATCH_FORUM_CONFIRM'		=> 'Сигурни ли сте, че искате да прекратите абонамента си за този форум?',
	'UNWATCH_FORUM_DETAILED'	=> 'Сигурни ли сте, че искате да прекратите абонамента си за форума “%s”?',
	'UNWATCH_TOPIC_CONFIRM'		=> 'Сигурни ли сте, че искате да прекратите абонамента си за тази тема?',
	'UNWATCH_TOPIC_DETAILED'	=> 'Сигурни ли сте, че искате да прекратите абонамента си за темата “%s”?',
	'UNWATCHED_FORUMS'			=> 'Успешно прекратихте абонамента си за избраните форуми.',
	'UNWATCHED_TOPICS'			=> 'Успешно прекратихте абонамента си за избраните теми.',
	'UNWATCHED_FORUMS_TOPICS'	=> 'Успешно прекратихте абонамента си за избраните теми/форуми.',
	'UPDATE'				=> 'Обнови',
	'UPLOAD_IN_PROGRESS'	=> 'В момента тече процес на качване.',
	'URL_REDIRECT'			=> 'Ако браузърът Ви не поддържа мета пренасочване %sмоля щракнете ТУК за да бъдете пренасочен%s.',
	'USERGROUPS'			=> 'Групи',
	'USERNAME'				=> 'Потребителско име',
	'USERNAMES'				=> 'Потребители',
	'USER_AVATAR'			=> 'Потребителски аватар',
	'USER_CANNOT_READ'		=> 'Не можете да четете мнения в този форум.',
	'USER_POSTS'			=> array(
		1	=> '%d мнение',
		2	=> '%d мнения',
	),
	'USERS'					=> 'Потребители',
	'USE_PERMISSIONS'		=> 'Изпробвай потребителските настройки и права',

	'USER_NEW_PERMISSION_DISALLOWED'	=> 'Съжаляваме, но не Ви е разрешено да използвате тази функция. Възможно е да сте регистрирали скоро и ще трябва да участвате по-дълго за да можете да използвате тази функция.',

	'VARIANT_DATE_SEPARATOR'	=> ' / ',	// Used in date format dropdown, eg: "Today, 13:37 / 01 Jan 2007, 13:37" ... to join a relative date with calendar date
	'VIEWED'					=> 'Преглеждания',
	'VIEWED_COUNTS'		=> array(
		0	=> 'Все още не е преглеждана',
		1	=> 'Видяна %d път',
		2	=> 'Видяна %d пъти',
	),
	'VIEWING_CONTACT_ADMIN'		=> 'Преглежда страницата за контакти',
	'VIEWING_FAQ'				=> 'Преглежда ЧЗВ',
	'VIEWING_MEMBERS'			=> 'Преглежда детайлите на потребител',
	'VIEWING_ONLINE'			=> 'Преглежда кой е на линия',
	'VIEWING_MCP'				=> 'Преглежда модераторския контролен панел',
	'VIEWING_MEMBER_PROFILE'	=> 'Преглежда профила на потребител',
	'VIEWING_PRIVATE_MESSAGES'	=> 'Преглежда личните съобщения',
	'VIEWING_REGISTER'			=> 'Регистрира потребителски профил',
	'VIEWING_UCP'				=> 'Преглежда потребителския контролен панел',
	'VIEWS'						=> 'Преглеждания',
	'VIEW_BOOKMARKS'			=> 'Виж любимите',
	'VIEW_FORUM_LOGS'			=> 'Виж логовете',
	'VIEW_LATEST_POST'			=> 'Виж последните мнения',
	'VIEW_NEWEST_POST'			=> 'Виж първите непрочетени мнения',
	'VIEW_NOTES'				=> 'Виж бележките на потребителя',
	'VIEW_ONLINE_TIMES'			=> array(
		1	=> 'базирано на активните потребители в последната %d минута',
		2	=> 'базирано на активните потребители в последните %d минути',
	),
	'VIEW_TOPIC'				=> 'Виж темата',
	'VIEW_TOPIC_ANNOUNCEMENT'	=> 'Известия: ',
	'VIEW_TOPIC_GLOBAL'			=> 'Глобални известия: ',
	'VIEW_TOPIC_LOCKED'			=> 'Заключена: ',
	'VIEW_TOPIC_LOGS'			=> 'Виж логовете',
	'VIEW_TOPIC_MOVED'			=> 'Преместена: ',
	'VIEW_TOPIC_POLL'			=> 'Анкета: ',
	'VIEW_TOPIC_STICKY'			=> 'Закачена: ',
	'VISIT_WEBSITE'				=> 'Посети сайта',

	'WARNINGS'			=> 'Предупреждения',
	'WARN_USER'			=> 'Сложи предупреждение',
	'WATCH_FORUM_CONFIRM'	=> 'Сигурни ли сте, че искате да се абонирате за този форум?',
	'WATCH_FORUM_DETAILED'	=> 'Сигурни ли сте, че искате да се абонирате за форума “%s”?',
	'WATCH_TOPIC_CONFIRM'	=> 'Сигурни ли сте, че искате да се абонирате за тази тема?',
	'WATCH_TOPIC_DETAILED'	=> 'Сигурни ли сте, че искате да се абонирате за темата “%s”?',
	'WELCOME_SUBJECT'	=> 'Добре дошли в %s форума',
	'WEBSITE'			=> 'Сайт',
	'WHOIS'				=> 'Whois',
	'WHO_IS_ONLINE'		=> 'Кой е на линия',
	'WLM'				=> 'WLM',
	'WRONG_PASSWORD'	=> 'Въведохте грешна парола.',

	'WRONG_DATA_COLOUR'			=> 'Цветовият код, който въведохте е невалиден.',
	'WRONG_DATA_JABBER'			=> 'Името, което въведохте не е валидно Jabber потребителско име.',
	'WRONG_DATA_LANG'			=> 'Езикът, който избрахте е невалиден.',
	'WRONG_DATA_POST_SD'		=> 'Избраният ред за сортиране на мнения не е невалиден.',
	'WRONG_DATA_POST_SK'		=> 'Избраният метод за сортиране на мнения не е невалиден.',
	'WRONG_DATA_TOPIC_SD'		=> 'Избраният ред за сортиране на теми не е невалиден.',
	'WRONG_DATA_TOPIC_SK'		=> 'Избраният метод за сортиране на теми не е невалиден.',
	'WROTE'						=> 'написа',

	'YAHOO'				=> 'Yahoo Messenger',
	'YOUTUBE'			=> 'YouTube',
	'YEAR'				=> 'Година',
	'YEAR_MONTH_DAY'	=> '(ГГГГ-ММ-ДД)',
	'YES'				=> 'Да',
	'YOU_LAST_VISIT'	=> 'Последно посещение: %s',

	'datetime'			=> array(
		'TODAY'		=> 'Днес',
		'TOMORROW'	=> 'Утре',
		'YESTERDAY'	=> 'Вчера',
		'AGO'		=> array(
			0		=> 'преди по-малко от минута',
			1		=> 'преди %d минута',
			2		=> 'преди %d минути',
		),

		'Sunday'	=> 'неделя',
		'Monday'	=> 'понеделник',
		'Tuesday'	=> 'вторник',
		'Wednesday'	=> 'сряда',
		'Thursday'	=> 'четвъртък',
		'Friday'	=> 'петък',
		'Saturday'	=> 'събота',

		'Sun'		=> 'нед',
		'Mon'		=> 'пон',
		'Tue'		=> 'вт',
		'Wed'		=> 'ср',
		'Thu'		=> 'чет',
		'Fri'		=> 'пет',
		'Sat'		=> 'съб',

		'January'	=> 'януари',
		'February'	=> 'февруари',
		'March'		=> 'март',
		'April'		=> 'април',
		'May'		=> 'май',
		'June'		=> 'юни',
		'July'		=> 'юли',
		'August'	=> 'август',
		'September' => 'септември',
		'October'	=> 'октомври',
		'November'	=> 'ноември',
		'December'	=> 'декемрви',

		'Jan'		=> 'яну',
		'Feb'		=> 'фев',
		'Mar'		=> 'мар',
		'Apr'		=> 'апр',
		'May_short'	=> 'май',	// Short representation of "May". May_short used because in English the short and long date are the same for May.
		'Jun'		=> 'юни',
		'Jul'		=> 'юли',
		'Aug'		=> 'авг',
		'Sep'		=> 'сеп',
		'Oct'		=> 'окт',
		'Nov'		=> 'ное',
		'Dec'		=> 'дек',
	),

	// Timezones can be translated. We use this for the Etc/GMT timezones here,
	// because they are named invers to their offset.
	'timezones'		=> array(
		'UTC'					=> 'UTC',
		'UTC_OFFSET'			=> 'UTC%1$s',
		'UTC_OFFSET_CURRENT'	=> 'UTC%1$s - %2$s',

		'Etc/GMT-12'	=> 'UTC+12',
		'Etc/GMT-11'	=> 'UTC+11',
		'Etc/GMT-10'	=> 'UTC+10',
		'Etc/GMT-9'		=> 'UTC+9',
		'Etc/GMT-8'		=> 'UTC+8',
		'Etc/GMT-7'		=> 'UTC+7',
		'Etc/GMT-6'		=> 'UTC+6',
		'Etc/GMT-5'		=> 'UTC+5',
		'Etc/GMT-4'		=> 'UTC+4',
		'Etc/GMT-3'		=> 'UTC+3',
		'Etc/GMT-2'		=> 'UTC+2',
		'Etc/GMT-1'		=> 'UTC+1',
		'Etc/GMT+1'		=> 'UTC-1',
		'Etc/GMT+2'		=> 'UTC-2',
		'Etc/GMT+3'		=> 'UTC-3',
		'Etc/GMT+4'		=> 'UTC-4',
		'Etc/GMT+5'		=> 'UTC-5',
		'Etc/GMT+6'		=> 'UTC-6',
		'Etc/GMT+7'		=> 'UTC-7',
		'Etc/GMT+8'		=> 'UTC-8',
		'Etc/GMT+9'		=> 'UTC-9',
		'Etc/GMT+10'	=> 'UTC-10',
		'Etc/GMT+11'	=> 'UTC-11',
		'Etc/GMT+12'	=> 'UTC-12',

		'Africa/Abidjan'	=> 'Африка/Abidjan',
		'Africa/Accra'		=> 'Африка/Accra',
		'Africa/Addis_Ababa'	=> 'Африка/Addis Ababa',
		'Africa/Algiers'	=> 'Африка/Algiers',
		'Africa/Asmara'		=> 'Африка/Asmara',
		'Africa/Bamako'		=> 'Африка/Bamako',
		'Africa/Bangui'		=> 'Африка/Bangui',
		'Africa/Banjul'		=> 'Африка/Banjul',
		'Africa/Bissau'		=> 'Африка/Bissau',
		'Africa/Blantyre'	=> 'Африка/Blantyre',
		'Africa/Brazzaville'	=> 'Африка/Brazzaville',
		'Africa/Bujumbura'	=> 'Африка/Bujumbura',
		'Africa/Cairo'		=> 'Африка/Cairo',
		'Africa/Casablanca'	=> 'Африка/Casablanca',
		'Africa/Ceuta'		=> 'Африка/Ceuta',
		'Africa/Conakry'	=> 'Африка/Conakry',
		'Africa/Dakar'		=> 'Африка/Dakar',
		'Africa/Dar_es_Salaam'	=> 'Африка/Dar es Salaam',
		'Africa/Djibouti'	=> 'Африка/Djibouti',
		'Africa/Douala'		=> 'Африка/Douala',
		'Africa/El_Aaiun'	=> 'Африка/El Aaiun',
		'Africa/Freetown'	=> 'Африка/Freetown',
		'Africa/Gaborone'	=> 'Африка/Gaborone',
		'Africa/Harare'		=> 'Африка/Harare',
		'Africa/Johannesburg'	=> 'Африка/Johannesburg',
		'Africa/Juba'		=> 'Африка/Juba',
		'Africa/Kampala'	=> 'Африка/Kampala',
		'Africa/Khartoum'	=> 'Африка/Khartoum',
		'Africa/Kigali'		=> 'Африка/Kigali',
		'Africa/Kinshasa'	=> 'Африка/Kinshasa',
		'Africa/Lagos'		=> 'Африка/Lagos',
		'Africa/Libreville'	=> 'Африка/Libreville',
		'Africa/Lome'		=> 'Африка/Lome',
		'Africa/Luanda'		=> 'Африка/Luanda',
		'Africa/Lubumbashi'	=> 'Африка/Lubumbashi',
		'Africa/Lusaka'		=> 'Африка/Lusaka',
		'Africa/Malabo'		=> 'Африка/Malabo',
		'Africa/Maputo'		=> 'Африка/Maputo',
		'Africa/Maseru'		=> 'Африка/Maseru',
		'Africa/Mbabane'	=> 'Африка/Mbabane',
		'Africa/Mogadishu'	=> 'Африка/Mogadishu',
		'Africa/Monrovia'	=> 'Африка/Monrovia',
		'Africa/Nairobi'	=> 'Африка/Nairobi',
		'Africa/Ndjamena'	=> 'Африка/Ndjamena',
		'Africa/Niamey'		=> 'Африка/Niamey',
		'Africa/Nouakchott'	=> 'Африка/Nouakchott',
		'Africa/Ouagadougou'	=> 'Африка/Ouagadougou',
		'Africa/Porto-Novo'	=> 'Африка/Porto-Novo',
		'Africa/Sao_Tome'	=> 'Африка/Sao Tome',
		'Africa/Tripoli'	=> 'Африка/Tripoli',
		'Africa/Tunis'		=> 'Африка/Tunis',
		'Africa/Windhoek'	=> 'Африка/Windhoek',

		'America/Adak'		=> 'America/Adak',
		'America/Anchorage'	=> 'America/Anchorage',
		'America/Anguilla'	=> 'America/Anguilla',
		'America/Antigua'	=> 'America/Antigua',
		'America/Araguaina'	=> 'America/Araguaina',

		'America/Argentina/Buenos_Aires'	=> 'America/Argentina/Buenos Aires',
		'America/Argentina/Catamarca'	=> 'America/Argentina/Catamarca',
		'America/Argentina/Cordoba'		=> 'America/Argentina/Cordoba',
		'America/Argentina/Jujuy'		=> 'America/Argentina/Jujuy',
		'America/Argentina/La_Rioja'	=> 'America/Argentina/La Rioja',
		'America/Argentina/Mendoza'		=> 'America/Argentina/Mendoza',
		'America/Argentina/Rio_Gallegos'	=> 'America/Argentina/Rio Gallegos',
		'America/Argentina/Salta'		=> 'America/Argentina/Salta',
		'America/Argentina/San_Juan'	=> 'America/Argentina/San Juan',
		'America/Argentina/San_Luis'	=> 'America/Argentina/San Luis',
		'America/Argentina/Tucuman'		=> 'America/Argentina/Tucuman',
		'America/Argentina/Ushuaia'		=> 'America/Argentina/Ushuaia',

		'America/Aruba'			=> 'America/Aruba',
		'America/Asuncion'		=> 'America/Asuncion',
		'America/Atikokan'		=> 'America/Atikokan',
		'America/Bahia'			=> 'America/Bahia',
		'America/Bahia_Banderas'	=> 'America/Bahia Banderas',
		'America/Barbados'		=> 'America/Barbados',
		'America/Belem'			=> 'America/Belem',
		'America/Belize'		=> 'America/Belize',
		'America/Blanc-Sablon'	=> 'America/Blanc-Sablon',
		'America/Boa_Vista'		=> 'America/Boa Vista',
		'America/Bogota'		=> 'America/Bogota',
		'America/Boise'			=> 'America/Boise',
		'America/Cambridge_Bay'	=> 'America/Cambridge Bay',
		'America/Campo_Grande'	=> 'America/Campo Grande',
		'America/Cancun'		=> 'America/Cancun',
		'America/Caracas'		=> 'America/Caracas',
		'America/Cayenne'		=> 'America/Cayenne',
		'America/Cayman'		=> 'America/Cayman',
		'America/Chicago'		=> 'America/Chicago',
		'America/Chihuahua'		=> 'America/Chihuahua',
		'America/Costa_Rica'	=> 'America/Costa Rica',
		'America/Creston'		=> 'America/Creston',
		'America/Cuiaba'		=> 'America/Cuiaba',
		'America/Curacao'		=> 'America/Curacao',
		'America/Danmarkshavn'	=> 'America/Danmarkshavn',
		'America/Dawson'		=> 'America/Dawson',
		'America/Dawson_Creek'	=> 'America/Dawson Creek',
		'America/Denver'		=> 'America/Denver',
		'America/Detroit'		=> 'America/Detroit',
		'America/Dominica'		=> 'America/Dominica',
		'America/Edmonton'		=> 'America/Edmonton',
		'America/Eirunepe'		=> 'America/Eirunepe',
		'America/El_Salvador'	=> 'America/El Salvador',
		'America/Fortaleza'		=> 'America/Fortaleza',
		'America/Glace_Bay'		=> 'America/Glace Bay',
		'America/Godthab'		=> 'America/Godthab',
		'America/Goose_Bay'		=> 'America/Goose Bay',
		'America/Grand_Turk'	=> 'America/Grand Turk',
		'America/Grenada'		=> 'America/Grenada',
		'America/Guadeloupe'	=> 'America/Guadeloupe',
		'America/Guatemala'		=> 'America/Guatemala',
		'America/Guayaquil'		=> 'America/Guayaquil',
		'America/Guyana'		=> 'America/Guyana',
		'America/Halifax'		=> 'America/Halifax',
		'America/Havana'		=> 'America/Havana',
		'America/Hermosillo'		=> 'America/Hermosillo',
		'America/Indiana/Indianapolis'	=> 'America/Indiana/Indianapolis',
		'America/Indiana/Knox'		=> 'America/Indiana/Knox',
		'America/Indiana/Marengo'	=> 'America/Indiana/Marengo',
		'America/Indiana/Petersburg'	=> 'America/Indiana/Petersburg',
		'America/Indiana/Tell_City'	=> 'America/Indiana/Tell City',
		'America/Indiana/Vevay'		=> 'America/Indiana/Vevay',
		'America/Indiana/Vincennes'	=> 'America/Indiana/Vincennes',
		'America/Indiana/Winamac'	=> 'America/Indiana/Winamac',
		'America/Inuvik'		=> 'America/Inuvik',
		'America/Iqaluit'		=> 'America/Iqaluit',
		'America/Jamaica'		=> 'America/Jamaica',
		'America/Juneau'		=> 'America/Juneau',
		'America/Kentucky/Louisville'	=> 'America/Kentucky/Louisville',
		'America/Kentucky/Monticello'	=> 'America/Kentucky/Monticello',
		'America/Kralendijk'	=> 'America/Kralendijk',
		'America/La_Paz'		=> 'America/La Paz',
		'America/Lima'			=> 'America/Lima',
		'America/Los_Angeles'	=> 'America/Los Angeles',
		'America/Lower_Princes'	=> 'America/Lower Princes',
		'America/Maceio'		=> 'America/Maceio',
		'America/Managua'		=> 'America/Managua',
		'America/Manaus'		=> 'America/Manaus',
		'America/Marigot'		=> 'America/Marigot',
		'America/Martinique'	=> 'America/Martinique',
		'America/Matamoros'		=> 'America/Matamoros',
		'America/Mazatlan'		=> 'America/Mazatlan',
		'America/Menominee'		=> 'America/Menominee',
		'America/Merida'		=> 'America/Merida',
		'America/Metlakatla'	=> 'America/Metlakatla',
		'America/Mexico_City'	=> 'America/Mexico City',
		'America/Miquelon'		=> 'America/Miquelon',
		'America/Moncton'		=> 'America/Moncton',
		'America/Monterrey'		=> 'America/Monterrey',
		'America/Montevideo'	=> 'America/Montevideo',
		'America/Montreal'		=> 'America/Montreal',
		'America/Montserrat'	=> 'America/Montserrat',
		'America/Nassau'		=> 'America/Nassau',
		'America/New_York'		=> 'America/New York',
		'America/Nipigon'		=> 'America/Nipigon',
		'America/Nome'			=> 'America/Nome',
		'America/Noronha'		=> 'America/Noronha',
		'America/North_Dakota/Beulah'		=> 'America/North Dakota/Beulah',
		'America/North_Dakota/Center'		=> 'America/North Dakota/Center',
		'America/North_Dakota/New_Salem'	=> 'America/North Dakota/New Salem',
		'America/Ojinaga'		=> 'America/Ojinaga',
		'America/Panama'		=> 'America/Panama',
		'America/Pangnirtung'	=> 'America/Pangnirtung',
		'America/Paramaribo'	=> 'America/Paramaribo',
		'America/Phoenix'		=> 'America/Phoenix',
		'America/Port-au-Prince'	=> 'America/Port-au-Prince',
		'America/Port_of_Spain'	=> 'America/Port of Spain',
		'America/Porto_Velho'	=> 'America/Porto Velho',
		'America/Puerto_Rico'	=> 'America/Puerto Rico',
		'America/Rainy_River'	=> 'America/Rainy River',
		'America/Rankin_Inlet'	=> 'America/Rankin Inlet',
		'America/Recife'		=> 'America/Recife',
		'America/Regina'		=> 'America/Regina',
		'America/Resolute'		=> 'America/Resolute',
		'America/Rio_Branco'	=> 'America/Rio Branco',
		'America/Santa_Isabel'	=> 'America/Santa Isabel',
		'America/Santarem'		=> 'America/Santarem',
		'America/Santiago'		=> 'America/Santiago',
		'America/Santo_Domingo'	=> 'America/Santo Domingo',
		'America/Sao_Paulo'		=> 'America/Sao Paulo',
		'America/Scoresbysund'	=> 'America/Scoresbysund',
		'America/Shiprock'		=> 'America/Shiprock',
		'America/Sitka'			=> 'America/Sitka',
		'America/St_Barthelemy'	=> 'America/St. Barthelemy',
		'America/St_Johns'		=> 'America/St. Johns',
		'America/St_Kitts'		=> 'America/St. Kitts',
		'America/St_Lucia'		=> 'America/St. Lucia',
		'America/St_Thomas'		=> 'America/St. Thomas',
		'America/St_Vincent'	=> 'America/St. Vincent',
		'America/Swift_Current'	=> 'America/Swift Current',
		'America/Tegucigalpa'	=> 'America/Tegucigalpa',
		'America/Thule'			=> 'America/Thule',
		'America/Thunder_Bay'	=> 'America/Thunder Bay',
		'America/Tijuana'		=> 'America/Tijuana',
		'America/Toronto'		=> 'America/Toronto',
		'America/Tortola'		=> 'America/Tortola',
		'America/Vancouver'		=> 'America/Vancouver',
		'America/Whitehorse'	=> 'America/Whitehorse',
		'America/Winnipeg'		=> 'America/Winnipeg',
		'America/Yakutat'		=> 'America/Yakutat',
		'America/Yellowknife'	=> 'America/Yellowknife',

		'Antarctica/Casey'		=> 'Antarctica/Casey',
		'Antarctica/Davis'		=> 'Antarctica/Davis',
		'Antarctica/DumontDUrville'	=> 'Antarctica/DumontDUrville',
		'Antarctica/Macquarie'	=> 'Antarctica/Macquarie',
		'Antarctica/Mawson'		=> 'Antarctica/Mawson',
		'Antarctica/McMurdo'	=> 'Antarctica/McMurdo',
		'Antarctica/Palmer'		=> 'Antarctica/Palmer',
		'Antarctica/Rothera'	=> 'Antarctica/Rothera',
		'Antarctica/South_Pole'	=> 'Antarctica/South Pole',
		'Antarctica/Syowa'		=> 'Antarctica/Syowa',
		'Antarctica/Vostok'		=> 'Antarctica/Vostok',

		'Arctic/Longyearbyen'	=> 'Arctic/Longyearbyen',

		'Asia/Aden'			=> 'Asia/Aden',
		'Asia/Almaty'		=> 'Asia/Almaty',
		'Asia/Amman'		=> 'Asia/Amman',
		'Asia/Anadyr'		=> 'Asia/Anadyr',
		'Asia/Aqtau'		=> 'Asia/Aqtau',
		'Asia/Aqtobe'		=> 'Asia/Aqtobe',
		'Asia/Ashgabat'		=> 'Asia/Ashgabat',
		'Asia/Baghdad'		=> 'Asia/Baghdad',
		'Asia/Bahrain'		=> 'Asia/Bahrain',
		'Asia/Baku'			=> 'Asia/Baku',
		'Asia/Bangkok'		=> 'Asia/Bangkok',
		'Asia/Beirut'		=> 'Asia/Beirut',
		'Asia/Bishkek'		=> 'Asia/Bishkek',
		'Asia/Brunei'		=> 'Asia/Brunei',
		'Asia/Choibalsan'	=> 'Asia/Choibalsan',
		'Asia/Chongqing'	=> 'Asia/Chongqing',
		'Asia/Colombo'		=> 'Asia/Colombo',
		'Asia/Damascus'		=> 'Asia/Damascus',
		'Asia/Dhaka'		=> 'Asia/Dhaka',
		'Asia/Dili'			=> 'Asia/Dili',
		'Asia/Dubai'		=> 'Asia/Dubai',
		'Asia/Dushanbe'		=> 'Asia/Dushanbe',
		'Asia/Gaza'			=> 'Asia/Gaza',
		'Asia/Harbin'		=> 'Asia/Harbin',
		'Asia/Hebron'		=> 'Asia/Hebron',
		'Asia/Ho_Chi_Minh'	=> 'Asia/Ho Chi Minh',
		'Asia/Hong_Kong'	=> 'Asia/Hong Kong',
		'Asia/Hovd'			=> 'Asia/Hovd',
		'Asia/Irkutsk'		=> 'Asia/Irkutsk',
		'Asia/Jakarta'		=> 'Asia/Jakarta',
		'Asia/Jayapura'		=> 'Asia/Jayapura',
		'Asia/Jerusalem'	=> 'Asia/Jerusalem',
		'Asia/Kabul'		=> 'Asia/Kabul',
		'Asia/Kamchatka'	=> 'Asia/Kamchatka',
		'Asia/Karachi'		=> 'Asia/Karachi',
		'Asia/Kashgar'		=> 'Asia/Kashgar',
		'Asia/Kathmandu'	=> 'Asia/Kathmandu',
		'Asia/Khandyga'		=> 'Asia/Khandyga',
		'Asia/Kolkata'		=> 'Asia/Kolkata',
		'Asia/Krasnoyarsk'	=> 'Asia/Krasnoyarsk',
		'Asia/Kuala_Lumpur'	=> 'Asia/Kuala Lumpur',
		'Asia/Kuching'		=> 'Asia/Kuching',
		'Asia/Kuwait'		=> 'Asia/Kuwait',
		'Asia/Macau'		=> 'Asia/Macau',
		'Asia/Magadan'		=> 'Asia/Magadan',
		'Asia/Makassar'		=> 'Asia/Makassar',
		'Asia/Manila'		=> 'Asia/Manila',
		'Asia/Muscat'		=> 'Asia/Muscat',
		'Asia/Nicosia'		=> 'Asia/Nicosia',
		'Asia/Novokuznetsk'	=> 'Asia/Novokuznetsk',
		'Asia/Novosibirsk'	=> 'Asia/Novosibirsk',
		'Asia/Omsk'			=> 'Asia/Omsk',
		'Asia/Oral'			=> 'Asia/Oral',
		'Asia/Phnom_Penh'	=> 'Asia/Phnom Penh',
		'Asia/Pontianak'	=> 'Asia/Pontianak',
		'Asia/Pyongyang'	=> 'Asia/Pyongyang',
		'Asia/Qatar'		=> 'Asia/Qatar',
		'Asia/Qyzylorda'	=> 'Asia/Qyzylorda',
		'Asia/Rangoon'		=> 'Asia/Rangoon',
		'Asia/Riyadh'		=> 'Asia/Riyadh',
		'Asia/Sakhalin'		=> 'Asia/Sakhalin',
		'Asia/Samarkand'	=> 'Asia/Samarkand',
		'Asia/Seoul'		=> 'Asia/Seoul',
		'Asia/Shanghai'		=> 'Asia/Shanghai',
		'Asia/Singapore'	=> 'Asia/Singapore',
		'Asia/Taipei'		=> 'Asia/Taipei',
		'Asia/Tashkent'		=> 'Asia/Tashkent',
		'Asia/Tbilisi'		=> 'Asia/Tbilisi',
		'Asia/Tehran'		=> 'Asia/Tehran',
		'Asia/Thimphu'		=> 'Asia/Thimphu',
		'Asia/Tokyo'		=> 'Asia/Tokyo',
		'Asia/Ulaanbaatar'	=> 'Asia/Ulaanbaatar',
		'Asia/Urumqi'		=> 'Asia/Urumqi',
		'Asia/Ust-Nera'		=> 'Asia/Ust-Nera',
		'Asia/Vientiane'	=> 'Asia/Vientiane',
		'Asia/Vladivostok'	=> 'Asia/Vladivostok',
		'Asia/Yakutsk'		=> 'Asia/Yakutsk',
		'Asia/Yekaterinburg'	=> 'Asia/Yekaterinburg',
		'Asia/Yerevan'		=> 'Asia/Yerevan',

		'Atlantic/Azores'		=> 'Atlantic/Azores',
		'Atlantic/Bermuda'		=> 'Atlantic/Bermuda',
		'Atlantic/Canary'		=> 'Atlantic/Canary',
		'Atlantic/Cape_Verde'	=> 'Atlantic/Cape Verde',
		'Atlantic/Faroe'		=> 'Atlantic/Faroe',
		'Atlantic/Madeira'		=> 'Atlantic/Madeira',
		'Atlantic/Reykjavik'	=> 'Atlantic/Reykjavik',
		'Atlantic/South_Georgia'	=> 'Atlantic/South Georgia',
		'Atlantic/St_Helena'	=> 'Atlantic/St. Helena',
		'Atlantic/Stanley'		=> 'Atlantic/Stanley',

		'Australia/Adelaide'	=> 'Australia/Adelaide',
		'Australia/Brisbane'	=> 'Australia/Brisbane',
		'Australia/Broken_Hill'	=> 'Australia/Broken Hill',
		'Australia/Currie'		=> 'Australia/Currie',
		'Australia/Darwin'		=> 'Australia/Darwin',
		'Australia/Eucla'		=> 'Australia/Eucla',
		'Australia/Hobart'		=> 'Australia/Hobart',
		'Australia/Lindeman'	=> 'Australia/Lindeman',
		'Australia/Lord_Howe'	=> 'Australia/Lord Howe',
		'Australia/Melbourne'	=> 'Australia/Melbourne',
		'Australia/Perth'		=> 'Australia/Perth',
		'Australia/Sydney'		=> 'Australia/Sydney',

		'Europe/Amsterdam'	=> 'Europe/Amsterdam',
		'Europe/Andorra'	=> 'Europe/Andorra',
		'Europe/Athens'		=> 'Europe/Athens',
		'Europe/Belgrade'	=> 'Europe/Belgrade',
		'Europe/Berlin'		=> 'Europe/Berlin',
		'Europe/Bratislava'	=> 'Europe/Bratislava',
		'Europe/Brussels'	=> 'Europe/Brussels',
		'Europe/Bucharest'	=> 'Europe/Bucharest',
		'Europe/Budapest'	=> 'Europe/Budapest',
		'Europe/Busingen'	=> 'Europe/Busingen',
		'Europe/Chisinau'	=> 'Europe/Chisinau',
		'Europe/Copenhagen'	=> 'Europe/Copenhagen',
		'Europe/Dublin'		=> 'Europe/Dublin',
		'Europe/Gibraltar'	=> 'Europe/Gibraltar',
		'Europe/Guernsey'	=> 'Europe/Guernsey',
		'Europe/Helsinki'	=> 'Europe/Helsinki',
		'Europe/Isle_of_Man'	=> 'Europe/Isle of Man',
		'Europe/Istanbul'	=> 'Europe/Istanbul',
		'Europe/Jersey'		=> 'Europe/Jersey',
		'Europe/Kaliningrad'	=> 'Europe/Kaliningrad',
		'Europe/Kiev'		=> 'Europe/Kiev',
		'Europe/Lisbon'		=> 'Europe/Lisbon',
		'Europe/Ljubljana'	=> 'Europe/Ljubljana',
		'Europe/London'		=> 'Europe/London',
		'Europe/Luxembourg'	=> 'Europe/Luxembourg',
		'Europe/Madrid'		=> 'Europe/Madrid',
		'Europe/Malta'		=> 'Europe/Malta',
		'Europe/Mariehamn'	=> 'Europe/Mariehamn',
		'Europe/Minsk'		=> 'Europe/Minsk',
		'Europe/Monaco'		=> 'Europe/Monaco',
		'Europe/Moscow'		=> 'Europe/Moscow',
		'Europe/Oslo'		=> 'Europe/Oslo',
		'Europe/Paris'		=> 'Europe/Paris',
		'Europe/Podgorica'	=> 'Europe/Podgorica',
		'Europe/Prague'		=> 'Europe/Prague',
		'Europe/Riga'		=> 'Europe/Riga',
		'Europe/Rome'		=> 'Europe/Rome',
		'Europe/Samara'		=> 'Europe/Samara',
		'Europe/San_Marino'	=> 'Europe/San Marino',
		'Europe/Sarajevo'	=> 'Europe/Sarajevo',
		'Europe/Simferopol'	=> 'Europe/Simferopol',
		'Europe/Skopje'		=> 'Europe/Skopje',
		'Europe/Sofia'		=> 'Europe/Sofia',
		'Europe/Stockholm'	=> 'Europe/Stockholm',
		'Europe/Tallinn'	=> 'Europe/Tallinn',
		'Europe/Tirane'		=> 'Europe/Tirane',
		'Europe/Uzhgorod'	=> 'Europe/Uzhgorod',
		'Europe/Vaduz'		=> 'Europe/Vaduz',
		'Europe/Vatican'	=> 'Europe/Vatican',
		'Europe/Vienna'		=> 'Europe/Vienna',
		'Europe/Vilnius'	=> 'Europe/Vilnius',
		'Europe/Volgograd'	=> 'Europe/Volgograd',
		'Europe/Warsaw'		=> 'Europe/Warsaw',
		'Europe/Zagreb'		=> 'Europe/Zagreb',
		'Europe/Zaporozhye'	=> 'Europe/Zaporozhye',
		'Europe/Zurich'		=> 'Europe/Zurich',

		'Indian/Antananarivo'	=> 'Indian/Antananarivo',
		'Indian/Chagos'		=> 'Indian/Chagos',
		'Indian/Christmas'	=> 'Indian/Christmas',
		'Indian/Cocos'		=> 'Indian/Cocos',
		'Indian/Comoro'		=> 'Indian/Comoro',
		'Indian/Kerguelen'	=> 'Indian/Kerguelen',
		'Indian/Mahe'		=> 'Indian/Mahe',
		'Indian/Maldives'	=> 'Indian/Maldives',
		'Indian/Mauritius'	=> 'Indian/Mauritius',
		'Indian/Mayotte'	=> 'Indian/Mayotte',
		'Indian/Reunion'	=> 'Indian/Reunion',

		'Pacific/Apia'		=> 'Pacific/Apia',
		'Pacific/Auckland'	=> 'Pacific/Auckland',
		'Pacific/Chatham'	=> 'Pacific/Chatham',
		'Pacific/Chuuk'		=> 'Pacific/Chuuk',
		'Pacific/Easter'	=> 'Pacific/Easter',
		'Pacific/Efate'		=> 'Pacific/Efate',
		'Pacific/Enderbury'	=> 'Pacific/Enderbury',
		'Pacific/Fakaofo'	=> 'Pacific/Fakaofo',
		'Pacific/Fiji'		=> 'Pacific/Fiji',
		'Pacific/Funafuti'	=> 'Pacific/Funafuti',
		'Pacific/Galapagos'	=> 'Pacific/Galapagos',
		'Pacific/Gambier'	=> 'Pacific/Gambier',
		'Pacific/Guadalcanal'	=> 'Pacific/Guadalcanal',
		'Pacific/Guam'		=> 'Pacific/Guam',
		'Pacific/Honolulu'	=> 'Pacific/Honolulu',
		'Pacific/Johnston'	=> 'Pacific/Johnston',
		'Pacific/Kiritimati'	=> 'Pacific/Kiritimati',
		'Pacific/Kosrae'	=> 'Pacific/Kosrae',
		'Pacific/Kwajalein'	=> 'Pacific/Kwajalein',
		'Pacific/Majuro'	=> 'Pacific/Majuro',
		'Pacific/Marquesas'	=> 'Pacific/Marquesas',
		'Pacific/Midway'	=> 'Pacific/Midway',
		'Pacific/Nauru'		=> 'Pacific/Nauru',
		'Pacific/Niue'		=> 'Pacific/Niue',
		'Pacific/Norfolk'	=> 'Pacific/Norfolk',
		'Pacific/Noumea'	=> 'Pacific/Noumea',
		'Pacific/Pago_Pago'	=> 'Pacific/Pago Pago',
		'Pacific/Palau'		=> 'Pacific/Palau',
		'Pacific/Pitcairn'	=> 'Pacific/Pitcairn',
		'Pacific/Pohnpei'	=> 'Pacific/Pohnpei',
		'Pacific/Port_Moresby'	=> 'Pacific/Port Moresby',
		'Pacific/Rarotonga'	=> 'Pacific/Rarotonga',
		'Pacific/Saipan'	=> 'Pacific/Saipan',
		'Pacific/Tahiti'	=> 'Pacific/Tahiti',
		'Pacific/Tarawa'	=> 'Pacific/Tarawa',
		'Pacific/Tongatapu'	=> 'Pacific/Tongatapu',
		'Pacific/Wake'		=> 'Pacific/Wake',
		'Pacific/Wallis'	=> 'Pacific/Wallis',
	),

	// The value is only an example and will get replaced by the current time on view
	'dateformats'	=> array(
		'd M Y, H:i'			=> '01 Jan 2007, 13:37',
		'd M Y H:i'				=> '01 Jan 2007 13:37',
		'M jS, \'y, H:i'		=> 'Jan 1st, \'07, 13:37',
		'D M d, Y g:i a'		=> 'Mon Jan 01, 2007 1:37 pm',
		'F jS, Y, g:i a'		=> 'January 1st, 2007, 1:37 pm',
		'|d M Y|, H:i'			=> 'Today, 13:37 / 01 Jan 2007, 13:37',
		'|F jS, Y|, g:i a'		=> 'Today, 1:37 pm / January 1st, 2007, 1:37 pm',
	),

	// The default dateformat which will be used on new installs in this language
	// Translators should change this if a the usual date format is different
	'default_dateformat'	=> 'D, d M Y, H:i', // Пон, 01 Ян 2007, 13:37

));
