<?php
/**
*
* This file is part of the phpBB Forum Software package.
*
* @copyright (c) phpBB Limited <https://www.phpbb.com>
* @license GNU General Public License, version 2 (GPL-2.0)
*
* For full copyright and license information, please see
* the docs/CREDITS.txt file.
*
*/

/**
* DO NOT CHANGE
*/
if (!defined('IN_PHPBB'))
{
	exit;
}

if (empty($lang) || !is_array($lang))
{
	$lang = array();
}

// DEVELOPERS PLEASE NOTE
//
// All language files should use UTF-8 as their encoding and the files must not contain a BOM.
//
// Placeholders can now contain order information, e.g. instead of
// 'Page %s of %s' you can (and should) write 'Page %1$s of %2$s', this allows
// translators to re-order the output of data while ensuring it remains correct
//
// You do not need this where single placeholders are used, e.g. 'Message %d' is fine
// equally where a string contains only two placeholders which are used to wrap text
// in a url you again do not need to specify an order e.g., 'Click %sHERE%s' is fine

// Privacy policy and T&C
$lang = array_merge($lang, array(
	'TERMS_OF_USE_CONTENT'	=> 'С влизането Ви в “%1$s” (наричан по-долу още “сайта”, “форума”, “ни”, “домейна”, “%1$s”, “%2$s”), Вие се съгласявате със следните условия. Ако не сте съгласни с всички правила, моля не влизайте и/или използвайте “%1$s”. Имаме право да променим тези правила по всяко време и ще направим всичко по силите си да Ви уведомим ако това се случи, но въпреки това Ви съветваме да преглеждате правилата редовно, тъй като ползването на “%1$s” след като са направени промени в правилата значи, че се съгласявате с тези промени.<br />
	<br />
	Нашият форум е базиран на phpBB (наричан по-долу още “те”, “техният”, “phpBB софтуер”, “www.phpbb.com”, “phpBB Limited”, “phpBB Teams”) което е форумна платформа пусната под “<a href="http://opensource.org/licenses/gpl-2.0.php">GNU General Public License v2</a>” (наричан по-долу “GPL”) и може да бъде свалена от <a href="https://www.phpbb.com/">www.phpbb.com</a>. phpBB софтуерът само улеснява Интернет базираните дискусии; phpBB Limited не е отговорна за това какво се разрешава и/или какво не се разрешава като съдържание и държание. За повече информация относно phpBB, моля посетете: <a href="https://www.phpbb.com/">https://www.phpbb.com/</a>.<br />
	<br />
	Съгласявате се да не публикувате обидни, нецензурни, вулгарни, клеветнически, предизвикващи омраза, заплашителни, сексуално ориентирани, насаждащи етническа омраза и други материали, които нарушават законите на Република България или Международното Право. Ако го направите, това може да доведе до незабавното Ви и постоянно изгонване и сезиране на Интернет провайдера Ви, ако това ни се стори наложително. IP адресите на всички мнения се записват за да помогнат за спазването на тези правила. Вие се съгласявате, че “%1$s” има правото да премахва, променя, премества или затваря всяка тема, по всяко време и по собствена преценка. Като потребител, Вие се съгласявате, че всяка информация, която публикувате ще бъде записвана в база данни. Въпреки, че тази информация няма да бъде споделяна с трети лица без Ваше съгласие, “%1$s” или phpBB не могат да бъдат държани отговорни за хакерски атаки, които могат да доведат до компрометиране на данните.
	',

	'PRIVACY_POLICY'		=> 'Следният текст обяснява в детайли как “%1$s” (наричан по-долу “сайта”, “форума”, “ни”, “домейна”, “%1$s”, “%2$s”) и phpBB (наричан по-долу още “те”, “техният”, “phpBB софтуер”, “www.phpbb.com”, “phpBB Limited”, “phpBB Teams”) използват всяка информация събрана по време на всяка потребителска сесия (наричана “Вашата информация”).<br />
	<br />
	Вашата информация се събира по два начина. Първо, при сърфиране в “%1$s” phpBB софтуерът ще създаде определен брой “бисквитки”, които са малки текстови файлове, които се свалят във временната папка на Вашият уеб браузър. Първите две бисквитки съдържат само потребителска идентификация (наричана по-долу “потребителско ID”) и анонимен сесиен идентификатор (наричан по-долу “ID на сесията”), който Ви е автоматично присвоен от phpBB софтуера. Трета бисквитка ще бъде създадена щом започнете да разглеждате теми в “%1$s” и се използва за се следи кои теми сте прочели и да се подобри потребителското изживяване.<br />
	<br />
	Също така можем да създаваме бисквитки, докато сърфирате в “%1$s”, които са външни за phpBB софтуера, тези бисквитки обаче са извън обхвата на този документ, който е предназначен да покрие само страниците създадени от phpBB софтуера. Вторият начин, по който събираме информация е чрез това, което изпращате към нас. Това може да бъде, но не се ограничава само до: публикуване като анонимен потребител (наричано още “анонимни мнения”), регистрация на “%1$s” (наричано още “Вашият профил”) и мнения, публикувани от Вас след регистрация (наричани още “Вашите мнения”).<br />
	<br />
	Вашият профил, като абсолютен минимум ще съдържа уникално идентификационно име (наричано още “Вашето потребителско име”), лична парола, използвана за влизане във Вашия профил (наричана още “Вашата парола”) и личен, валиден емейл адрес (наричан още “Вашият емейл”). Информацията за Вашият профил в “%1$s” е защитена от Закона за защита на личните данни на Република България. Всяка информация освен Вашето потребителско име, Вашата парола и Вашият емейл адрес въведена по време на регистрацията може да бъде задължителна или незадължителна по преценка на “%1$s”. Във всички случаи, Вие имате правото да определяте коя информация от Вашият профил да бъде публично достъпна. Също така, във Вашият профил, имате възможността да включите или изключите получаването на автоматично генерирани емейли от phpBB софтуера.<br />
	<br />
	Вашата парола е криптирана (с еднопосочен хеш) за да бъде защитена. Въпреки това е препоръчително да не използвате една и съща парола в различни сайтове. Вашата парола е начинът Ви за достъп до профилът Ви в “%1$s”, затова, моля, пазете я внимателно. При никакви обстоятелства, никой свързан с “%1$s”, phpBB или трето лице, няма право да Ви пита за паролата Ви. Ако забравите паролата за профила си, можете да използвате “Забравих си паролата” фукцията, предоставена от phpBB софтуера. При този процес, ще Ви бъде поискано да въведете потребителското си име и емейл, след което phpBB софтуерът ще генерира нова парола за да достъпите отново профила си.<br />
	',
));

// Common language entries
$lang = array_merge($lang, array(
	'ACCOUNT_ACTIVE'				=> 'Профилът Ви беше активиран. Благодарим Ви, че се регистрирахте.',
	'ACCOUNT_ACTIVE_ADMIN'			=> 'Профилът Ви беше активиран.',
	'ACCOUNT_ACTIVE_PROFILE'		=> 'Профилът Ви беше успешно реактивиран.',
	'ACCOUNT_ADDED'					=> 'Благодарим Ви за регистрацията, профилът Ви беше създаден. Можете да влезете с потребителското си име и парола.',
	'ACCOUNT_COPPA'					=> 'Профилът Ви беше създаден, но трябва да бъде одобрен, моля проверете емейла си за повече подробности.',
	'ACCOUNT_EMAIL_CHANGED'			=> 'Профилът Ви беше обновен. Форумът изисква реактивация на профила при промяна на емейл адреса. Активационен код беше изпратен на новия емейл адрес, който посочихте. Моля, проверете си пощата за повече информация.',
	'ACCOUNT_EMAIL_CHANGED_ADMIN'	=> 'Профилът Ви беше обновен. Форумът изисква реактивация на профила от администратор при промяна на емейл адреса. Ще Ви бъде изпратен емейл, когато профилът Ви бъде реактивиран.',
	'ACCOUNT_INACTIVE'				=> 'Профилът Ви беше създаден. Форумът изисква активация на профила. Активационен код беше изпратен на емейл адреса, който посочихте. Моля, проверете си пощата за повече информация.',
	'ACCOUNT_INACTIVE_ADMIN'		=> 'Профилът Ви беше създаден. Форумът изисква активация на профила от администраторската група. Беше им изпратен емейл, а Вие ще бъдете уведомени когато профилът Ви е активиран.',
	'ACTIVATION_EMAIL_SENT'			=> 'Активационния емейл беше изпратен до Вашият емейл адрес.',
	'ACTIVATION_EMAIL_SENT_ADMIN'	=> 'Активационния емейл беше изпратен до емейл адреса на администратора.',
	'ADD'							=> 'Добави',
	'ADD_BCC'						=> 'Добави [СК]',
	'ADD_FOES'						=> 'Добави нови врагове',
	'ADD_FOES_EXPLAIN'				=> 'Можете да въведете няколко потребителски имена, всяко на нов ред.',
	'ADD_FOLDER'					=> 'Създай папка',
	'ADD_FRIENDS'					=> 'Добави нови приятели',
	'ADD_FRIENDS_EXPLAIN'			=> 'Можете да въведете няколко потребителски имена, всяко на нов ред.',
	'ADD_NEW_RULE'					=> 'Добави ново правило',
	'ADD_RULE'						=> 'Добави правило',
	'ADD_TO'						=> 'Добави [До]',
	'ADD_USERS_UCP_EXPLAIN'			=> 'Тук можете да добавяте нови потребители към групата. Можете да избирате дали тази група да стане групата по подразбиране за избраните потребители. Моля, въвеждайте по едно потребителско име на ред.',
	'ADMIN_EMAIL'					=> 'Администраторите могат да ми изпращат информация по емейл',
	'AGREE'							=> 'Съгласен съм с тези условия',
	'ALLOW_PM'						=> 'Потребителите могат да ми изпращат лични съобщения',
	'ALLOW_PM_EXPLAIN'				=> 'Обърнете внимание, че администраторите и модераторите ще могат винаги да Ви изпращат лични съобщения.',
	'ALREADY_ACTIVATED'				=> 'Вашият профил вече е бил активиран.',
	'ATTACHMENTS_EXPLAIN'			=> 'Това е списък с файловете, които сте прикачили във всички мнения във форума.',
	'ATTACHMENTS_DELETED'			=> 'Прикачените файлове бяха успешно изтрити.',
	'ATTACHMENT_DELETED'			=> 'Прикаченият файл беше успешно изтрит.',
	'AUTOLOGIN_SESSION_KEYS_DELETED'=> 'Избраните "Запомни ме" ключове за влизане бяха успешно изтрити.',
	'AVATAR_CATEGORY'				=> 'Категория',
	'AVATAR_DRIVER_GRAVATAR_TITLE'	=> 'Gravatar',
	'AVATAR_DRIVER_GRAVATAR_EXPLAIN'=> 'Gravatar е услуга, която Ви позволява да поддържате един и същи аватар в различни уебсайтове. Посетете <a href="http://www.gravatar.com/">Gravatar</a> за повече информация.',
	'AVATAR_DRIVER_LOCAL_TITLE'		=> 'Галерия с аватари',
	'AVATAR_DRIVER_LOCAL_EXPLAIN'	=> 'Можете да избирете аватарт от наличните в локалната галерия.',
	'AVATAR_DRIVER_REMOTE_TITLE'	=> 'Аватар от друг сайт',
	'AVATAR_DRIVER_REMOTE_EXPLAIN'	=> 'Връзка към снимка от друг уебсайт.',
	'AVATAR_DRIVER_UPLOAD_TITLE'	=> 'Качване на собствен аватар',
	'AVATAR_DRIVER_UPLOAD_EXPLAIN'	=> 'Качете свой собствен аватар.',
	'AVATAR_EXPLAIN'				=> 'Максимални размери; ширина: %1$s, височина: %2$s, размер на файла: %3$.2f KiB.',
	'AVATAR_FEATURES_DISABLED'		=> 'Аватарите в момента са забранени.',
	'AVATAR_GALLERY'				=> 'Локална галерия',
	'AVATAR_GENERAL_UPLOAD_ERROR'	=> 'Аватарът не може да бъде качен в %s.',
	'AVATAR_NOT_ALLOWED'			=> 'Аватарът Ви не може да бъде показан, защото аватарите са забранени.',
	'AVATAR_PAGE'					=> 'Страница',
	'AVATAR_SELECT'					=> 'Изберете своя аватар',
	'AVATAR_TYPE'					=> 'Тип на аватара',
	'AVATAR_TYPE_NOT_ALLOWED'		=> 'Аватарът Ви не може да бъде показа, защото типът му не е разрешен.',

	'BACK_TO_DRAFTS'			=> 'Върнете се към запазените чернови',
	'BACK_TO_LOGIN'				=> 'Върнете се на страницата за вход',
	'BIRTHDAY'					=> 'Рожден ден',
	'BIRTHDAY_EXPLAIN'			=> 'Указвайки година, възрастта Ви ще се показва до потребителското Ви име, когато имате рожден ден.',
	'BOARD_DATE_FORMAT'			=> 'Формат на датата',
	'BOARD_DATE_FORMAT_EXPLAIN'	=> 'Синтаксисът, който се използва е идентичен с този на PHP <a href="http://www.php.net/date">date()</a> функцията.',
	'BOARD_LANGUAGE'			=> 'Език',
	'BOARD_STYLE'				=> 'Стил на форума',
	'BOARD_TIMEZONE'			=> 'Часова зона',
	'BOOKMARKS'					=> 'Любими теми',
	'BOOKMARKS_EXPLAIN'			=> 'Можете да маркирате теми като любими за бъдеща справка. Изберете темите, които искате да премахнете от любими и натиснете <em>Изтрий избраните теми от любими</em> бутона.',
	'BOOKMARKS_DISABLED'		=> 'Любимите теми са забранени в този форум.',
	'BOOKMARKS_REMOVED'			=> 'Избраните теми бяха премахнати от любими.',

	'CANNOT_EDIT_MESSAGE_TIME'	=> 'Вече не можете да променяте или изтриете това съобщение.',
	'CANNOT_MOVE_TO_SAME_FOLDER'=> 'Съобщенията не могат да бъдат преместени в папката, която желаете да изтриете.',
	'CANNOT_MOVE_FROM_SPECIAL'	=> 'Съобщенията от изходящата кутия не могат да бъдат местени.',
	'CANNOT_RENAME_FOLDER'		=> 'Тази папка не може да бъде преименувана.',
	'CANNOT_REMOVE_FOLDER'		=> 'Тази папка не може да бъде изтрита.',
	'CHANGE_DEFAULT_GROUP'		=> 'Промени групата по подразбиране',
	'CHANGE_PASSWORD'			=> 'Промени паролата',
	'CLICK_GOTO_FOLDER'			=> '%1$sОтиди в “%3$s” папката%2$s',
	'CLICK_RETURN_FOLDER'		=> '%1$sВърни се в “%3$s” папката%2$s',
	'CONFIRMATION'				=> 'Потвърждение за регистрация',
	'CONFIRM_CHANGES'			=> 'Потвърдете промените',
	'CONFIRM_EXPLAIN'			=> 'За да предотврати автоматични регистрации, форумът изисква да въведете потвърждаващ код. Кодът е показан на изображението, което трябва да видите долу. Ако имате проблеми със зрението и не можете да прочетете кода по друг начин, моля свържете се с  %sАдминистратора%s.',
	'VC_REFRESH'				=> 'Презареди потвърждаващия код',
	'VC_REFRESH_EXPLAIN'		=> 'Ако не можете да прочетете кода можете да заредите нов като натиснете бутона.',

	'CONFIRM_PASSWORD'			=> 'Потвърдете паролата',
	'CONFIRM_PASSWORD_EXPLAIN'	=> 'Трябва да потвърдите паролата си само ако сте я променили горе.',
	'COPPA_BIRTHDAY'			=> 'За да продължите с регистрацията, моля въведете рождената си дата.',
	'COPPA_COMPLIANCE'			=> 'Съответствие с COPPA',
	'COPPA_EXPLAIN'				=> 'Обърнете внимание, че с натискане на бутона за изпращане ние ще създадем Ваш профил. Въпреки това, той няма да е активен докато родител или настойник не одобри и потвърди Вашата регистрация. На посоченият емейл адрес ще Ви бъдат изпратени копия на нужните документи с детайли за това къде трябва да бъдат изпратени.',
	'CREATE_FOLDER'				=> 'Създай папка…',
	'CURRENT_IMAGE'				=> 'Сегашен аватар',
	'CURRENT_PASSWORD'			=> 'Сегашна парола',
	'CURRENT_PASSWORD_EXPLAIN'	=> 'Трябва да въведете сегашната си парола, ако искате да смените емейл адреса или потребителското си име.',
	'CURRENT_CHANGE_PASSWORD_EXPLAIN' => 'За да си смените паролата, емейл адреса или потребителското, трябва да въведете сегашната си парола.',
	'CUR_PASSWORD_EMPTY'		=> 'Не сте въвели сегашната си парола.',
	'CUR_PASSWORD_ERROR'		=> 'Паролата, която въведохте е грешна.',
	'CUSTOM_DATEFORMAT'			=> 'Собствен формат…',

	'DEFAULT_ACTION'			=> 'Действие по подразбиране',
	'DEFAULT_ACTION_EXPLAIN'	=> 'Това действие ще бъде изпълнено ако никое от горните не е приложимо.',
	'DEFAULT_ADD_SIG'			=> 'Винаги добавяй подписа ми',
	'DEFAULT_BBCODE'			=> 'Винаги разрешавай BBCode',
	'DEFAULT_NOTIFY'			=> 'Винаги ме уведомявай за нови отговори',
	'DEFAULT_SMILIES'			=> 'Винаги разрешавай усмивките',
	'DEFINED_RULES'				=> 'Дефинирани правила',
	'DELETED_TOPIC'				=> 'Темата е била изтрита.',
	'DELETE_ATTACHMENT'			=> 'Изтрий прикачения файл',
	'DELETE_ATTACHMENTS'		=> 'Изтрий прикачените файлове',
	'DELETE_ATTACHMENT_CONFIRM'	=> 'Сигурни ли сте, че искате да изтриете прикачения файл?',
	'DELETE_ATTACHMENTS_CONFIRM'=> 'Сигурни ли сте, че искате да изтриете прикачените файлове?',
	'DELETE_AVATAR'				=> 'Изтрий аватара',
	'DELETE_COOKIES_CONFIRM'	=> 'Сигурни ли сте, че искате да изтриете всички бисквитки записани от форума?',
	'DELETE_MARKED_PM'			=> 'Изтрий избраните съобщения',
	'DELETE_MARKED_PM_CONFIRM'	=> 'Сигурни ли сте, че искате да изтриете всички избрани съобщения?',
	'DELETE_OLDEST_MESSAGES'	=> 'Изтрий най-старите съобщения',
	'DELETE_MESSAGE'			=> 'Изтрий съобщението',
	'DELETE_MESSAGE_CONFIRM'	=> 'Сигурни ли сте, че искате да изтриете това лично съобщение?',
	'DELETE_MESSAGES_IN_FOLDER'	=> 'Изтрий всички съобщения от изтритата папка',
	'DELETE_RULE'				=> 'Изтрий правилото',
	'DELETE_RULE_CONFIRM'		=> 'Сигурни ли сте, че искате да изтриете това правило?',
	'DEMOTE_SELECTED'			=> 'Понижи избраните',
	'DISABLE_CENSORS'			=> 'Разреши цензурирането на думи',
	'DISPLAY_GALLERY'			=> 'Покажи галерията',
	'DOMAIN_NO_MX_RECORD_EMAIL'	=> 'Въведеният емейл домейн няма валиден MX запис.',
	'DOWNLOADS'					=> 'Сваляния',
	'DRAFTS_DELETED'			=> 'Всички избрани чернови бяха успешно изтрити.',
	'DRAFTS_EXPLAIN'			=> 'Тук можете да преглеждате, редактирате и изтривате вашите запазени чернови.',
	'DRAFT_UPDATED'				=> 'Черновата беше успешно обновена.',

	'EDIT_DRAFT_EXPLAIN'		=> 'Тук можете да редактирате вашата чернова. Черновите не съдържат прикачени файлове и информация за анкети.',
	'EMAIL_BANNED_EMAIL'		=> 'Емейл адресът, който въведохте е забранен за използване.',
	'EMAIL_REMIND'				=> 'Това е емейл адресът асоцииран с вашият профил. Ако не сте го променяли от потребителския контролен панел, то това е емейл адресът, с който сте се регистрирали.',
	'EMAIL_TAKEN_EMAIL'			=> 'Въведеният емейл адрес вече се използва.',
	'EMPTY_DRAFT'				=> 'Трябва да въведете съобщение за да запазите промените.',
	'EMPTY_DRAFT_TITLE'			=> 'Трябва да въведете заглавие на черновата.',
	'EXPORT_AS_XML'				=> 'Експортирай като XML',
	'EXPORT_AS_CSV'				=> 'Експортирай като CSV',
	'EXPORT_AS_CSV_EXCEL'		=> 'Експортирай като CSV (Excel)',
	'EXPORT_AS_TXT'				=> 'Експортирай като TXT',
	'EXPORT_AS_MSG'				=> 'Експортирай като MSG',
	'EXPORT_FOLDER'				=> 'Експортирай този изглед',

	'FIELD_REQUIRED'					=> 'Полето “%s” трябва да е попълнено.',
	'FIELD_TOO_SHORT'					=> array(
		1	=> 'Полето “%2$s” е твърде късо, въведете поне %1$d символ.',
		2	=> 'Полето “%2$s” е твърде късо, въведете поне %1$d символа.',
	),
	'FIELD_TOO_LONG'					=> array(
		1	=> 'Полето “%2$s” е твърде дълго, въведете най-много %1$d символ.',
		2	=> 'Полето “%2$s” е твърде дълго, въведете най-много %1$d символа.',
	),
	'FIELD_TOO_SMALL'					=> 'The value of “%2$s” is too small, a minimum value of %1$d is required.',
	'FIELD_TOO_LARGE'					=> 'The value of “%2$s” is too large, a maximum value of %1$d is allowed.',
	'FIELD_INVALID_CHARS_INVALID'		=> 'The field “%s” has invalid characters.',
	'FIELD_INVALID_CHARS_NUMBERS_ONLY'	=> 'The field “%s” has invalid characters, only numbers are allowed.',
	'FIELD_INVALID_CHARS_ALPHA_DOTS'	=> 'The field “%s” has invalid characters, only alphanumeric or . characters are allowed.',
	'FIELD_INVALID_CHARS_ALPHA_ONLY'	=> 'The field “%s” has invalid characters, only alphanumeric characters are allowed.',
	'FIELD_INVALID_CHARS_ALPHA_PUNCTUATION'	=> 'The field “%s” has invalid characters, only alphanumeric or _,-. characters are allowed and the first character must be alphabetic.',
	'FIELD_INVALID_CHARS_ALPHA_SPACERS'	=> 'The field “%s” has invalid characters, only alphanumeric, space or -+_[] characters are allowed.',
	'FIELD_INVALID_CHARS_ALPHA_UNDERSCORE'	=> 'The field “%s” has invalid characters, only alphanumeric or _ characters are allowed.',
	'FIELD_INVALID_CHARS_LETTER_NUM_DOTS'	=> 'The field “%s” has invalid characters, only letter, number or . characters are allowed.',
	'FIELD_INVALID_CHARS_LETTER_NUM_ONLY'	=> 'The field “%s” has invalid characters, only letter and number characters are allowed.',
	'FIELD_INVALID_CHARS_LETTER_NUM_PUNCTUATION'	=> 'The field “%s” has invalid characters, only letter, number or _,-. characters are allowed and the first character must be alphabetic.',
	'FIELD_INVALID_CHARS_LETTER_NUM_SPACERS'		=> 'The field “%s” has invalid characters, only letter, number, space or -+_[] characters are allowed.',
	'FIELD_INVALID_CHARS_LETTER_NUM_UNDERSCORE'		=> 'The field “%s” has invalid characters, only letter, number or _ characters are allowed.',
	'FIELD_INVALID_DATE'				=> 'The field “%s” has an invalid date.',
	'FIELD_INVALID_URL'					=> 'The field “%s” has an invalid url.',
	'FIELD_INVALID_VALUE'				=> 'The field “%s” has an invalid value.',

	'FOE_MESSAGE'				=> 'Message from foe',
	'FOES_EXPLAIN'				=> 'Foes are users which will be ignored by default. Posts by these users will not be fully visible. Personal messages from foes are still permitted. Please note that you cannot ignore moderators or administrators.',
	'FOES_UPDATED'				=> 'Your foes list has been updated successfully.',
	'FOLDER_ADDED'				=> 'Folder successfully added.',
	'FOLDER_MESSAGE_STATUS'		=> array(
		1	=> '%2$d out of %1$s stored',
		2	=> '%2$d out of %1$s stored',
	),
	'FOLDER_NAME_EMPTY'			=> 'You must enter a name for this folder.',
	'FOLDER_NAME_EXIST'			=> 'Folder <strong>%s</strong> already exists.',
	'FOLDER_OPTIONS'			=> 'Folder options',
	'FOLDER_RENAMED'			=> 'Folder successfully renamed.',
	'FOLDER_REMOVED'			=> 'Folder successfully removed.',
	'FOLDER_STATUS_MSG'			=> array(
		1	=> 'Folder is %3$d%% full (%2$d out of %1$s stored)',
		2	=> 'Folder is %3$d%% full (%2$d out of %1$s stored)',
	),
	'FORWARD_PM'				=> 'Forward PM',
	'FORCE_PASSWORD_EXPLAIN'	=> 'Before you may continue browsing the board you are required to change your password.',
	'FRIEND_MESSAGE'			=> 'Message from friend',
	'FRIENDS'					=> 'Friends',
	'FRIENDS_EXPLAIN'			=> 'Friends enable you quick access to members you communicate with frequently. If the template has relevant support any posts made by a friend may be highlighted.',
	'FRIENDS_OFFLINE'			=> 'Offline',
	'FRIENDS_ONLINE'			=> 'Online',
	'FRIENDS_UPDATED'			=> 'Your friends list has been updated successfully.',
	'FULL_FOLDER_OPTION_CHANGED'=> 'The action to take when a folder is full has been changed successfully.',
	'FWD_ORIGINAL_MESSAGE'		=> '-------- Original Message --------',
	'FWD_SUBJECT'				=> 'Subject: %s',
	'FWD_DATE'					=> 'Date: %s',
	'FWD_FROM'					=> 'From: %s',
	'FWD_TO'					=> 'To: %s',

	'GLOBAL_ANNOUNCEMENT'		=> 'Global announcement',

	'GRAVATAR_AVATAR_EMAIL'			=> 'Gravatar email',
	'GRAVATAR_AVATAR_EMAIL_EXPLAIN'	=> 'Enter the email address you used for registering your account on <a href="http://www.gravatar.com/">Gravatar</a>.',
	'GRAVATAR_AVATAR_SIZE'			=> 'Avatar dimensions',
	'GRAVATAR_AVATAR_SIZE_EXPLAIN'	=> 'Specify the width and height of the avatar, leave blank to attempt automatic verification.',

	'HIDE_ONLINE'				=> 'Не показвай кога съм на линия',
	'HIDE_ONLINE_EXPLAIN'		=> 'Changing this setting won’t become effective until your next visit to the board.',
	'HOLD_NEW_MESSAGES'			=> 'Do not accept new messages (New messages will be held back until enough space is available)',
	'HOLD_NEW_MESSAGES_SHORT'	=> 'New messages will be held back',

	'IF_FOLDER_FULL'			=> 'If folder is full',
	'IMPORTANT_NEWS'			=> 'Important announcements',
	'INVALID_USER_BIRTHDAY'			=> 'The entered birthday is not a valid date.',
	'INVALID_CHARS_USERNAME'	=> 'The username contains forbidden characters.',
	'INVALID_CHARS_NEW_PASSWORD'=> 'The password does not contain the required characters.',
	'ITEMS_REQUIRED'			=> 'The items marked with * are required profile fields and need to be filled out.',

	'JOIN_SELECTED'				=> 'Join selected',

	'LANGUAGE'					=> 'Език',
	'LINK_REMOTE_AVATAR'		=> 'Link off-site',
	'LINK_REMOTE_AVATAR_EXPLAIN'=> 'Enter the URL of the location containing the avatar image you wish to link to.',
	'LINK_REMOTE_SIZE'			=> 'Avatar dimensions',
	'LINK_REMOTE_SIZE_EXPLAIN'	=> 'Specify the width and height of the avatar, leave blank to attempt automatic verification.',
	'LOGIN_EXPLAIN_UCP'			=> 'Please login in order to access the User Control Panel.',
	'LOGIN_LINK'					=> 'Link or register your account on an external service with your board account',
	'LOGIN_LINK_EXPLAIN'			=> 'You have attempted to login with an external service that is not yet connected to an account on this board. You must now either link this account to an existing account or create a new account.',
	'LOGIN_LINK_MISSING_DATA'		=> 'Data that is necessary to link your account with an external service is not available. Please restart the login process.',
	'LOGIN_LINK_NO_DATA_PROVIDED'	=> 'No data has been provided to this page to link an external account to a forum account. Please contact the board administrator if you continue to experience problems.',
	'LOGIN_KEY'					=> 'Login Key',
	'LOGIN_TIME'				=> 'Login Time',
	'LOGIN_REDIRECT'			=> 'Успешно влязохте в профила си.',
	'LOGOUT_FAILED'				=> 'You were not logged out, as the request did not match your session. Please contact the board administrator if you continue to experience problems.',
	'LOGOUT_REDIRECT'			=> 'Успешно излезнахте от профила си.',

	'MARK_IMPORTANT'				=> 'Mark/Unmark as important',
	'MARKED_MESSAGE'				=> 'Marked message',
	'MAX_FOLDER_REACHED'			=> 'Maximum number of allowed user defined folders reached.',
	'MESSAGE_BY_AUTHOR'				=> 'от',
	'MESSAGE_COLOURS'				=> 'Message colours',
	'MESSAGE_DELETED'				=> 'Message successfully deleted.',
	'MESSAGE_EDITED'				=> 'Message successfully edited.',
	'MESSAGE_HISTORY'				=> 'Message history',
	'MESSAGE_REMOVED_FROM_OUTBOX'	=> 'This message was deleted by its author.',
	'MESSAGE_SENT_ON'				=> 'на',
	'MESSAGE_STORED'				=> 'This message has been sent successfully.',
	'MESSAGE_TO'					=> 'До',
	'MESSAGES_DELETED'				=> 'Messages successfully deleted',
	'MOVE_DELETED_MESSAGES_TO'		=> 'Move messages from removed folder to',
	'MOVE_DOWN'						=> 'Move down',
	'MOVE_MARKED_TO_FOLDER'			=> 'Move marked to %s',
	'MOVE_PM_ERROR'					=> array(
		1	=> 'An error occurred while moving the messages to the new folder, only %2$d out of %1$s was moved.',
		2	=> 'An error occurred while moving the messages to the new folder, only %2$d out of %1$s were moved.',
	),
	'MOVE_TO_FOLDER'				=> 'Move to folder',
	'MOVE_UP'						=> 'Move up',

	'NEW_FOLDER_NAME'				=> 'New folder name',
	'NEW_PASSWORD'					=> 'New password',
	'NEW_PASSWORD_CONFIRM_EMPTY'	=> 'You did not enter a confirm password.',
	'NEW_PASSWORD_ERROR'			=> 'The passwords you entered do not match.',

	'NOTIFICATIONS_MARK_ALL_READ'						=> 'Маркирай всички известия като прочетени',
	'NOTIFICATIONS_MARK_ALL_READ_CONFIRM'				=> 'Сигурни ли сте, че искате да маркирате всички известия като прочетени?',
	'NOTIFICATIONS_MARK_ALL_READ_SUCCESS'				=> 'Всички известия бяха маркирани като прочетени.',
	'NOTIFICATION_GROUP_MISCELLANEOUS'					=> 'Разни известия',
	'NOTIFICATION_GROUP_MODERATION'						=> 'Модераторски известия',
	'NOTIFICATION_GROUP_ADMINISTRATION'					=> 'Администраторски известия',
	'NOTIFICATION_GROUP_POSTING'						=> 'Известия за публикации',
	'NOTIFICATION_METHOD_EMAIL'							=> 'Емейл',
	'NOTIFICATION_METHOD_JABBER'						=> 'Jabber',
	'NOTIFICATION_TYPE'									=> 'Тип на известието',
	'NOTIFICATION_TYPE_BOOKMARK'						=> 'Някой отговори на тема, която сте маркирали като любима',
	'NOTIFICATION_TYPE_GROUP_REQUEST'					=> 'Някой поиска да се присъедини към група, на която сте лидер',
	'NOTIFICATION_TYPE_IN_MODERATION_QUEUE'				=> 'Мнение или тема се нуждаят от одобрение',
	'NOTIFICATION_TYPE_MODERATION_QUEUE'				=> 'Ваше мнение/тема са одобрени или неодобрени от модератор',
	'NOTIFICATION_TYPE_PM'								=> 'Някой Ви изпрати лично съобщение',
	'NOTIFICATION_TYPE_POST'							=> 'Някой отговори на тема, за която сте абониран',
	'NOTIFICATION_TYPE_QUOTE'							=> 'Някой Ви цитира в мнение',
	'NOTIFICATION_TYPE_REPORT'							=> 'Някой докладва мнение',
	'NOTIFICATION_TYPE_TOPIC'							=> 'Някой създаде тема във форум, за който сте абониран',
	'NOTIFICATION_TYPE_ADMIN_ACTIVATE_USER'				=> 'Новорегистриран потребител, който изисква активация',

	'NOTIFY_METHOD'					=> 'Метод на известяване',
	'NOTIFY_METHOD_BOTH'			=> 'И двете',
	'NOTIFY_METHOD_EMAIL'			=> 'Само емейл',
	'NOTIFY_METHOD_EXPLAIN'			=> 'Method for sending messages sent via this board.',
	'NOTIFY_METHOD_IM'				=> 'Jabber only',
	'NOTIFY_ON_PM'					=> 'Notify me on new private messages',
	'NOT_ADDED_FRIENDS_ANONYMOUS'	=> 'You cannot add the anonymous user to your friends list.',
	'NOT_ADDED_FRIENDS_BOTS'		=> 'You cannot add bots to your friends list.',
	'NOT_ADDED_FRIENDS_FOES'		=> 'You cannot add users to your friends list who are on your foes list.',
	'NOT_ADDED_FRIENDS_SELF'		=> 'You cannot add yourself to the friends list.',
	'NOT_ADDED_FOES_MOD_ADMIN'		=> 'You cannot add administrators and moderators to your foes list.',
	'NOT_ADDED_FOES_ANONYMOUS'		=> 'You cannot add the anonymous user to your foes list.',
	'NOT_ADDED_FOES_BOTS'			=> 'You cannot add bots to your foes list.',
	'NOT_ADDED_FOES_FRIENDS'		=> 'You cannot add users to your foes list who are on your friends list.',
	'NOT_ADDED_FOES_SELF'			=> 'You cannot add yourself to the foes list.',
	'NOT_AGREE'						=> 'Не съм съгласен с тези правила',
	'NOT_ENOUGH_SPACE_FOLDER'		=> 'The destination folder “%s” seems to be full. The requested action has not been taken.',
	'NOT_MOVED_MESSAGES'			=> array(
		1	=> 'You have %d private message currently on hold because of full folder.',
		2	=> 'You have %d private messages currently on hold because of full folder.',
	),
	'NO_ACTION_MODE'				=> 'No message action specified.',
	'NO_AUTHOR'						=> 'No author defined for this message',
	'NO_AVATAR'						=> 'No avatar selected',
	'NO_AVATAR_CATEGORY'			=> 'None',

	'NO_AUTH_DELETE_MESSAGE'		=> 'You are not authorised to delete private messages.',
	'NO_AUTH_EDIT_MESSAGE'			=> 'You are not authorised to edit private messages.',
	'NO_AUTH_FORWARD_MESSAGE'		=> 'You are not authorised to forward private messages.',
	'NO_AUTH_GROUP_MESSAGE'			=> 'You are not authorised to send private messages to groups.',
	'NO_AUTH_PASSWORD_REMINDER'		=> 'You are not authorised to request a new password.',
	'NO_AUTH_PROFILEINFO'			=> 'You are not authorised to change your profile information.',
	'NO_AUTH_READ_HOLD_MESSAGE'		=> 'You are not authorised to read private messages that are on hold.',
	'NO_AUTH_READ_MESSAGE'			=> 'You are not authorised to read private messages.',
	'NO_AUTH_READ_REMOVED_MESSAGE'	=> 'You are not able to read this message because it was removed by the author.',
	'NO_AUTH_SEND_MESSAGE'			=> 'You are not authorised to send private messages.',
	'NO_AUTH_SIGNATURE'				=> 'You are not authorised to define a signature.',

	'NO_BCC_RECIPIENT'			=> 'None',
	'NO_BOOKMARKS'				=> 'You have no bookmarks.',
	'NO_BOOKMARKS_SELECTED'		=> 'You have selected no bookmarks.',
	'NO_EDIT_READ_MESSAGE'		=> 'Private message cannot be edited because it has already been read.',
	'NO_EMAIL_USER'				=> 'The email/username information submitted could not be found.',
	'NO_FOES'					=> 'No foes currently defined',
	'NO_FRIENDS'				=> 'No friends currently defined',
	'NO_FRIENDS_OFFLINE'		=> 'No friends offline',
	'NO_FRIENDS_ONLINE'			=> 'No friends online',
	'NO_GROUP_SELECTED'			=> 'No group specified.',
	'NO_IMPORTANT_NEWS'			=> 'No important announcements present.',
	'NO_MESSAGE'				=> 'Private message could not be found.',
	'NO_NEW_FOLDER_NAME'		=> 'You have to specify a new folder name.',
	'NO_NEWER_PM'				=> 'No newer messages.',
	'NO_OLDER_PM'				=> 'No older messages.',
	'NO_PASSWORD_SUPPLIED'		=> 'You cannot login without a password.',
	'NO_RECIPIENT'				=> 'No recipient defined.',
	'NO_RULES_DEFINED'			=> 'No rules defined.',
	'NO_SAVED_DRAFTS'			=> 'No drafts saved.',
	'NO_TO_RECIPIENT'			=> 'None',
	'NO_WATCHED_FORUMS'			=> 'You are not subscribed to any forums.',
	'NO_WATCHED_SELECTED'		=> 'You have not selected any subscribed topics or forums.',
	'NO_WATCHED_TOPICS'			=> 'You are not subscribed to any topics.',

	'PASS_TYPE_ALPHA_EXPLAIN'	=> 'Password must be between %1$s and %2$s long, must contain letters in mixed case and must contain numbers.',
	'PASS_TYPE_ANY_EXPLAIN'		=> 'Must be between %1$s and %2$s.',
	'PASS_TYPE_CASE_EXPLAIN'	=> 'Password must be between %1$s and %2$s long and must contain letters in mixed case.',
	'PASS_TYPE_SYMBOL_EXPLAIN'	=> 'Password must be between %1$s and %2$s long, must contain letters in mixed case, must contain numbers and must contain symbols.',
	'PASSWORD'					=> 'Парола',
	'PASSWORD_ACTIVATED'		=> 'Your new password has been activated.',
	'PASSWORD_UPDATED'			=> 'A new password was sent to your registered email address.',
	'PERMISSIONS_RESTORED'		=> 'Successfully restored original permissions.',
	'PERMISSIONS_TRANSFERRED'	=> 'Successfully transferred permissions from <strong>%s</strong>, you are now able to browse the board with this user’s permissions.<br />Please note that admin permissions were not transferred. You are able to revert to your permission set at any time.',
	'PM_DISABLED'				=> 'Private messaging has been disabled on this board.',
	'PM_FROM'					=> 'От',
	'PM_FROM_REMOVED_AUTHOR'	=> 'This message was sent by a user no longer registered.',
	'PM_ICON'					=> 'PM icon',
	'PM_INBOX'					=> 'Входяща кутия',
	'PM_MARK_ALL_READ'			=> 'Mark all messages read',
	'PM_MARK_ALL_READ_SUCCESS'	=> 'All private messages in this folder have been marked read',
	'PM_NO_USERS'				=> 'The requested users to be added do not exist.',
	'PM_OUTBOX'					=> 'Изходяща кутия',
	'PM_SENTBOX'				=> 'Изпратени съобщения',
	'PM_SUBJECT'				=> 'Message subject',
	'PM_TO'						=> 'Send to',
	'PM_TOOLS'					=> 'Message tools',
	'PM_USERS_REMOVED_NO_PERMISSION'	=> 'Some users couldn’t be added as they do not have permission to read private messages.',
	'PM_USERS_REMOVED_NO_PM'	=> 'Some users couldn’t be added as they have disabled private message receipt.',
	'POST_EDIT_PM'				=> 'Edit message',
	'POST_FORWARD_PM'			=> 'Forward message',
	'POST_NEW_PM'				=> 'Compose message',
	'POST_PM_LOCKED'			=> 'Private messaging is locked.',
	'POST_PM_POST'				=> 'Quote post',
	'POST_QUOTE_PM'				=> 'Quote message',
	'POST_REPLY_PM'				=> 'Reply to message',
	'PRINT_PM'					=> 'Print view',
	'PREFERENCES_UPDATED'		=> 'Your preferences have been updated.',
	'PROFILE_INFO_NOTICE'		=> 'Please note that this information may be viewable to other members. Be careful when including any personal details. Any fields marked with a * must be completed.',
	'PROFILE_UPDATED'			=> 'Your profile has been updated.',
	'PROFILE_AUTOLOGIN_KEYS'	=> 'The "Remember Me" login keys automatically log you in when you visit the board. If you logout, the remember me login key is deleted only on the computer you are using to logout. Here you can see remember login keys created on other computers you used to access this site.',
	'PROFILE_NO_AUTOLOGIN_KEYS'	=> 'There are no saved "Remember Me" login keys.',

	'RECIPIENT'							=> 'Получател',
	'RECIPIENTS'						=> 'Получатели',
	'REGISTRATION'						=> 'Регистрация',
	'RELEASE_MESSAGES'					=> '%sRelease all on-hold messages%s… they will be re-sorted into the appropriate folder if enough space is made available.',
	'REMOVE_ADDRESS'					=> 'Remove address',
	'REMOVE_SELECTED_BOOKMARKS'			=> 'Remove selected bookmarks',
	'REMOVE_SELECTED_BOOKMARKS_CONFIRM'	=> 'Are you sure you want to delete all selected bookmarks?',
	'REMOVE_BOOKMARK_MARKED'			=> 'Remove marked bookmarks',
	'REMOVE_FOLDER'						=> 'Remove folder',
	'REMOVE_FOLDER_CONFIRM'				=> 'Are you sure you want to remove this folder?',
	'RENAME'							=> 'Rename',
	'RENAME_FOLDER'						=> 'Rename folder',
	'REPLIED_MESSAGE'					=> 'Replied to message',
	'REPLY_TO_ALL'						=> 'Reply to sender and all recipients.',
	'REPORT_PM'							=> 'Report private message',
	'RESIGN_SELECTED'					=> 'Resign selected',
	'RETURN_FOLDER'						=> '%1$sReturn to previous folder%2$s',
	'RETURN_UCP'						=> '%sReturn to the User Control Panel%s',
	'RULE_ADDED'						=> 'Rule successfully added.',
	'RULE_ALREADY_DEFINED'				=> 'This rule was defined previously.',
	'RULE_DELETED'						=> 'Rule successfully removed.',
	'RULE_LIMIT_REACHED'				=> 'You cannot add more PM rules. You have reached the maximum number of rules.',
	'RULE_NOT_DEFINED'					=> 'Rule not correctly specified.',
	'RULE_REMOVED_MESSAGES'				=> array(
		1	=> '%d private message was removed due to private message filters.',
		2	=> '%d private messages were removed due to private message filters.',
	),

	'SAME_PASSWORD_ERROR'		=> 'The new password you entered is the same as your current password.',
	'SEARCH_YOUR_POSTS'			=> 'Show your posts',
	'SEND_PASSWORD'				=> 'Send password',
	'SENT_AT'					=> 'Изпратено на',			// Used before dates in private messages
	'SHOW_EMAIL'				=> 'Users can contact me by email',
	'SIGNATURE_EXPLAIN'			=> 'This is a block of text that can be added to posts you make. There is a %d character limit.',
	'SIGNATURE_PREVIEW'			=> 'Your signature will appear like this in posts',
	'SIGNATURE_TOO_LONG'		=> 'Your signature is too long.',
	'SELECT_CURRENT_TIME'		=> 'Select current time',
	'SELECT_TIMEZONE'			=> 'Select timezone',
	'SORT'						=> 'Sort',
	'SORT_COMMENT'				=> 'File comment',
	'SORT_DOWNLOADS'			=> 'Downloads',
	'SORT_EXTENSION'			=> 'Extension',
	'SORT_FILENAME'				=> 'Filename',
	'SORT_POST_TIME'			=> 'Post time',
	'SORT_SIZE'					=> 'File size',

	'TIMEZONE'					=> 'Timezone',
	'TIMEZONE_DATE_SUGGESTION'	=> 'Suggestion: %s',
	'TIMEZONE_INVALID'			=> 'The timezone you selected is invalid.',
	'TO'						=> 'Recipient',
	'TO_MASS'					=> 'Recipients',
	'TO_ADD'					=> 'Add recipient',
	'TO_ADD_MASS'				=> 'Add recipients',
	'TO_ADD_GROUPS'				=> 'Add groups',
	'TOO_MANY_RECIPIENTS'		=> 'You tried to send a private message to too many recipients.',
	'TOO_MANY_REGISTERS'		=> 'You have exceeded the maximum number of registration attempts for this session. Please try again later.',

	'UCP'						=> 'Потребителски контролен панел',
	'UCP_ACTIVATE'				=> 'Activate account',
	'UCP_ADMIN_ACTIVATE'		=> 'Please note that you will need to enter a valid email address before your account is activated. The administrator will review your account and if approved you will receive an email at the address you specified.',
	'UCP_ATTACHMENTS'			=> 'Прикачени файлове',
	'UCP_AUTH_LINK'				=> 'External accounts',
	'UCP_AUTH_LINK_ASK'			=> 'You currently have no account associated with this external service. Click the button below to link your board account to an account with this external service.',
	'UCP_AUTH_LINK_ID'			=> 'Unique identifier',
	'UCP_AUTH_LINK_LINK'		=> 'Link',
	'UCP_AUTH_LINK_MANAGE'		=> 'Manage external account associations',
	'UCP_AUTH_LINK_NOT_SUPPORTED'	=> 'Linking board accounts to external services is not supported by this board’s current authentication method.',
	'UCP_AUTH_LINK_TITLE'		=> 'Manage your external account associations',
	'UCP_AUTH_LINK_UNLINK'		=> 'Unlink',
	'UCP_COPPA_BEFORE'			=> 'Before %s',
	'UCP_COPPA_ON_AFTER'		=> 'On or after %s',
	'UCP_EMAIL_ACTIVATE'		=> 'Please note that you will need to enter a valid email address before your account is activated. You will receive an email at the address you provide that contains an account activation link.',
	'UCP_JABBER'				=> 'Jabber address',
	'UCP_LOGIN_LINK'			=> 'Set up an external account association',

	'UCP_MAIN'					=> 'Главна страница',
	'UCP_MAIN_ATTACHMENTS'		=> 'Управление на прикачените файлове',
	'UCP_MAIN_BOOKMARKS'		=> 'Управление на любимите теми',
	'UCP_MAIN_DRAFTS'			=> 'Управление на черновите',
	'UCP_MAIN_FRONT'			=> 'Главна страница',
	'UCP_MAIN_SUBSCRIBED'		=> 'Управление на абонаментите',

	'UCP_NO_ATTACHMENTS'		=> 'Нямате прикачени файлове.',

	'UCP_NOTIFICATION_LIST'				=> 'Управление на известията',
	'UCP_NOTIFICATION_LIST_EXPLAIN'		=> 'Here you may view all past notifications.',
	'UCP_NOTIFICATION_OPTIONS'			=> 'Edit notification options',
	'UCP_NOTIFICATION_OPTIONS_EXPLAIN'	=> 'Here you can set your preferred notification methods for the board.',

	'UCP_PREFS'					=> 'Настройки на форума',
	'UCP_PREFS_PERSONAL'		=> 'Edit global settings',
	'UCP_PREFS_POST'			=> 'Edit posting defaults',
	'UCP_PREFS_VIEW'			=> 'Edit display options',

	'UCP_PM'					=> 'Лични съобщения',
	'UCP_PM_COMPOSE'			=> 'Напиши съобщение',
	'UCP_PM_DRAFTS'				=> 'Управление на ЛС чернови',
	'UCP_PM_OPTIONS'			=> 'Rules, folders &amp; settings',
	'UCP_PM_UNREAD'				=> 'Непрочетени съобщения',
	'UCP_PM_VIEW'				=> 'Преглеждане на съобщенията от',

	'UCP_PROFILE'				=> 'Профил',
	'UCP_PROFILE_AVATAR'		=> 'Промяна на аватар',
	'UCP_PROFILE_PROFILE_INFO'	=> 'Промяна на профил',
	'UCP_PROFILE_REG_DETAILS'	=> 'Промяна на настройките',
	'UCP_PROFILE_SIGNATURE'		=> 'Промяна на подписа',
	'UCP_PROFILE_AUTOLOGIN_KEYS'=> 'Manage “Remember Me” login keys',

	'UCP_USERGROUPS'			=> 'Потребителски групи',
	'UCP_USERGROUPS_MEMBER'		=> 'Промяна на членствата',
	'UCP_USERGROUPS_MANAGE'		=> 'Управление на групите',

	'UCP_PASSWORD_RESET_DISABLED'	=> 'The password reset functionality has been disabled. If you need help accessing your account, please contact the %sBoard Administrator%s',
	'UCP_REGISTER_DISABLE'			=> 'Creating a new account is currently not possible.',
	'UCP_REMIND'					=> 'Send password',
	'UCP_RESEND'					=> 'Send activation email',
	'UCP_WELCOME'					=> 'Welcome to the User Control Panel. From here you can monitor, view and update your profile, preferences, subscribed forums and topics. You can also send messages to other users (if permitted). Please ensure you read any announcements before continuing.',
	'UCP_ZEBRA'						=> 'Приятели &amp; Врагове',
	'UCP_ZEBRA_FOES'				=> 'Manage foes',
	'UCP_ZEBRA_FRIENDS'				=> 'Manage friends',
	'UNDISCLOSED_RECIPIENT'			=> 'Undisclosed Recipient',
	'UNKNOWN_FOLDER'				=> 'Unknown folder',
	'UNWATCH_MARKED'				=> 'Unwatch marked',
	'UPLOAD_AVATAR_FILE'			=> 'Upload from your machine',
	'UPLOAD_AVATAR_URL'				=> 'Upload from a URL',
	'UPLOAD_AVATAR_URL_EXPLAIN'		=> 'Enter the URL of the location containing the image. The image will be copied to this site.',
	'USERNAME_ALPHA_ONLY_EXPLAIN'	=> 'Username must be between %1$s and %2$s long and use only alphanumeric characters.',
	'USERNAME_ALPHA_SPACERS_EXPLAIN'=> 'Username must be between %1$s and %2$s long and use alphanumeric, space or -+_[] characters.',
	'USERNAME_ASCII_EXPLAIN'		=> 'Username must be between %1$s and %2$s long and use only ASCII characters, so no special symbols.',
	'USERNAME_LETTER_NUM_EXPLAIN'	=> 'Username must be between %1$s and %2$s long and use only letter or number characters.',
	'USERNAME_LETTER_NUM_SPACERS_EXPLAIN'=> 'Username must be between %1$s and %2$s long and use letter, number, space or -+_[] characters.',
	'USERNAME_CHARS_ANY_EXPLAIN'	=> 'Length must be between %1$s and %2$s.',
	'USERNAME_TAKEN_USERNAME'		=> 'The username you entered is already in use, please select an alternative.',
	'USERNAME_DISALLOWED_USERNAME'	=> 'The username you entered has been disallowed or contains a disallowed word. Please choose a different name.',
	'USER_NOT_FOUND_OR_INACTIVE'	=> 'The usernames you specified could either not be found or are not activated users.',

	'VIEW_AVATARS'				=> 'Display avatars',
	'VIEW_EDIT'					=> 'View/Edit',
	'VIEW_FLASH'				=> 'Display Flash animations',
	'VIEW_IMAGES'				=> 'Display images within posts',
	'VIEW_NEXT_HISTORY'			=> 'Next PM in history',
	'VIEW_NEXT_PM'				=> 'Next PM',
	'VIEW_PM'					=> 'View message',
	'VIEW_PM_INFO'				=> 'Message details',
	'VIEW_PM_MESSAGES'			=> array(
		1	=> '%d message',
		2	=> '%d messages',
	),
	'VIEW_PREVIOUS_HISTORY'		=> 'Previous PM in history',
	'VIEW_PREVIOUS_PM'			=> 'Previous PM',
	'VIEW_PROFILE'				=> 'View profile',
	'VIEW_SIGS'					=> 'Display signatures',
	'VIEW_SMILIES'				=> 'Display smilies as images',
	'VIEW_TOPICS_DAYS'			=> 'Display topics from previous days',
	'VIEW_TOPICS_DIR'			=> 'Display topic order direction',
	'VIEW_TOPICS_KEY'			=> 'Display topics ordering by',
	'VIEW_POSTS_DAYS'			=> 'Display posts from previous days',
	'VIEW_POSTS_DIR'			=> 'Display post order direction',
	'VIEW_POSTS_KEY'			=> 'Display posts ordering by',

	'WATCHED_EXPLAIN'			=> 'Below is a list of forums and topics you are subscribed to. You will be notified of new posts in either. To unsubscribe mark the forum or topic and then press the <em>Unwatch marked</em> button.',
	'WATCHED_FORUMS'			=> 'Watched forums',
	'WATCHED_TOPICS'			=> 'Watched topics',
	'WRONG_ACTIVATION'			=> 'The activation key you supplied does not match any in the database.',

	'YOUR_DETAILS'				=> 'Your activity',
	'YOUR_FOES'					=> 'Your foes',
	'YOUR_FOES_EXPLAIN'			=> 'To remove usernames select them and click submit.',
	'YOUR_FRIENDS'				=> 'Your friends',
	'YOUR_FRIENDS_EXPLAIN'		=> 'To remove usernames select them and click submit.',
	'YOUR_WARNINGS'				=> 'Your warning level',

	'PM_ACTION' => array(
		'PLACE_INTO_FOLDER'	=> 'Place into folder',
		'MARK_AS_READ'		=> 'Mark as read',
		'MARK_AS_IMPORTANT'	=> 'Mark message',
		'DELETE_MESSAGE'	=> 'Delete message',
	),
	'PM_CHECK' => array(
		'SUBJECT'	=> 'Subject',
		'SENDER'	=> 'Sender',
		'MESSAGE'	=> 'Message',
		'STATUS'	=> 'Message status',
		'TO'		=> 'Sent To',
	),
	'PM_RULE' => array(
		'IS_LIKE'		=> 'is like',
		'IS_NOT_LIKE'	=> 'is not like',
		'IS'			=> 'is',
		'IS_NOT'		=> 'is not',
		'BEGINS_WITH'	=> 'begins with',
		'ENDS_WITH'		=> 'ends with',
		'IS_FRIEND'		=> 'is friend',
		'IS_FOE'		=> 'is foe',
		'IS_USER'		=> 'is user',
		'IS_GROUP'		=> 'is in usergroup',
		'ANSWERED'		=> 'answered',
		'FORWARDED'		=> 'forwarded',
		'TO_GROUP'		=> 'to my default usergroup',
		'TO_ME'			=> 'to me',
	),

	'GROUPS_EXPLAIN'	=> 'Usergroups enable board admins to better administer users. By default you will be placed in a specific group, this is your default group. This group defines how you may appear to other users, for example your username colouration, avatar, rank, etc. Depending on whether the administrator allows it you may be allowed to change your default group. You may also be placed in or allowed to join other groups. Some groups may give you additional permissions to view content or increase your capabilities in other areas.',
	'GROUP_LEADER'		=> 'Leaderships',
	'GROUP_MEMBER'		=> 'Memberships',
	'GROUP_PENDING'		=> 'Pending memberships',
	'GROUP_NONMEMBER'	=> 'Non-memberships',
	'GROUP_DETAILS'		=> 'Group details',

	'NO_LEADER'		=> 'No group leaderships',
	'NO_MEMBER'		=> 'No group memberships',
	'NO_PENDING'	=> 'No pending memberships',
	'NO_NONMEMBER'	=> 'No non-member groups',
));
